apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - node-exporter.yaml
  - prometheus-rbac.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - grafana.yaml
