@startuml Diagrama_Secuencia_Usuario_Registrado
title Diagrama de secuencia - Usuario Registrado

skinparam backgroundColor #1E1E1E
skinparam sequence {
    ArrowColor White
    LifeLineBorderColor White
    LifeLineBackgroundColor #7FA6D9
    ParticipantBorderColor White
    ParticipantBackgroundColor #7FA6D9
    ParticipantFontColor White
    ActorBorderColor White
    ActorFontColor White
    ActorBackgroundColor #1E1E1E
    DatabaseBorderColor White
    DatabaseBackgroundColor #8C8C8C
    DatabaseFontColor White
}
skinparam shadowing false
skinparam defaultFontColor White

actor "Usuario Registrado" as Usuario

participant "API Gateway" as Gateway
participant "Auth Service" as Auth
participant "Catalog Service" as Catalog
participant "Billing Service" as Billing
participant "FX Service" as FX
participant "Notification Service" as Notif

database "Auth DB" as UserDB
database "Catalog DB" as CatalogDB
database "Billing DB" as BillingDB

== Autenticación y Perfiles (CDU-N1) ==

Usuario -> Gateway : POST /auth/login (email, password)
Gateway -> Auth : gRPC Login(email, password)
Auth -> UserDB : Validar credenciales (email, hash)
UserDB --> Auth : OK
Auth -> Auth : Generar JWT
Auth --> Gateway : LoginResponse (access_token)
Gateway --> Usuario : 200 OK + JWT

Usuario -> Gateway : GET /auth/profiles (Headers: Bearer JWT)
Gateway -> Auth : Middleware: gRPC ValidarToken(JWT)
Auth --> Gateway : Token válido

Gateway -> Auth : gRPC ListarPerfiles(usuario_id)
Auth -> UserDB : Consultar perfiles
UserDB --> Auth : Lista de perfiles
Auth --> Gateway : ListarPerfilesResponse
Gateway --> Usuario : Muestra perfiles disponibles

== Exploración de Catálogo (CDU-N3) ==

Usuario -> Gateway : GET /catalog/cartelera
Gateway -> Auth : Middleware: ValidarToken
Gateway -> Catalog : gRPC ExplorarCartelera()
Catalog -> CatalogDB : Consultar contenido
CatalogDB --> Catalog : Resultados
Catalog --> Gateway : CarteleraResponse
Gateway --> Usuario : Muestra catálogo público

Usuario -> Gateway : Intenta reproducir contenido (CDU-N3-02)
Gateway --> Usuario : 403 Forbidden (Requiere Suscripción activa)

== Cotización y Suscripción (CDU-N2, CDU-N5, CDU-N7) ==

Usuario -> Gateway : POST /billing/plans/price (plan_id, moneda_local)
Gateway -> Billing : gRPC GetPlanPrice
Billing -> FX : gRPC CalcularTarifa(moneda_local)
FX --> Billing : Tarifa convertida a moneda local
Billing --> Gateway : Precio local
Gateway --> Usuario : Muestra precio en moneda local (CDU-N5-01)

Usuario -> Gateway : POST /billing/subscriptions (plan_id)
Gateway -> Billing : gRPC CreateSubscription()
Billing -> BillingDB : Registrar nueva suscripción
BillingDB --> Billing : Suscripción activa
Billing -> Notif : Emitir evento (Suscripción Creada)
Notif -> Notif : Servir Correo Electrónico (SMTP)
Billing --> Gateway : SuscriptionResponse
Gateway --> Usuario : 201 Created (Ahora es Usuario Suscriptor)

@enduml
