version: '3.8'

services:
  auth-service:
    image: ${DOCKERHUB_USERNAME}/quetxal-auth-service:latest
    container_name: quetxal-auth-service
    restart: always
    environment:
      NODE_ENV: production
      GRPC_PORT: 50051
      AUTH_DB_HOST: ${DB_VM_HOST:-127.0.0.1}
      AUTH_DB_PORT: ${AUTH_DB_PORT:-5432}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      DB_SSLMODE: disable
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-me}
      JWT_TTL_MIN: ${JWT_TTL_MIN:-60}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_ADDR:-notification-service:50054}
    ports:
      - "50051:50051"
    networks:
      - quetxal-net

  notification-service:
    image: ${DOCKERHUB_USERNAME}/quetxal-notification-service:latest
    container_name: quetxal-notification-service
    restart: always
    environment:
      NODE_ENV: production
      GRPC_PORT: 50054
      NOTIFICATION_DB_HOST: ${DB_VM_HOST:-127.0.0.1}
      NOTIFICATION_DB_PORT: ${NOTIFICATION_DB_PORT:-5438}
      NOTIFICATION_DB_NAME: ${NOTIFICATION_DB_NAME}
      NOTIFICATION_DB_USER: ${NOTIFICATION_DB_USER}
      NOTIFICATION_DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      DB_SSLMODE: disable
    ports:
      - "50054:50054"
    networks:
      - quetxal-net

networks:
  quetxal-net:
    driver: bridge
