name: quetxal-tv

services:

  auth-db:
    build: ./db/auth
    container_name: quetxal-auth-db
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  subscription-db:
    build: ./db/subscription
    container_name: quetxal-subscription-db
    restart: always
    environment:
      POSTGRES_DB: ${SUBSCRIPTION_DB_NAME}
      POSTGRES_USER: ${SUBSCRIPTION_DB_USER}
      POSTGRES_PASSWORD: ${SUBSCRIPTION_DB_PASSWORD}
    volumes:
      - subscription_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  catalog-db:
    build: ./db/catalog
    container_name: quetxal-catalog-db
    restart: always
    environment:
      POSTGRES_DB: ${CATALOG_DB_NAME}
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
    volumes:
      - catalog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  rating-db:
    build: ./db/rating
    container_name: quetxal-rating-db
    restart: always
    environment:
      POSTGRES_DB: ${RATING_DB_NAME}
      POSTGRES_USER: ${RATING_DB_USER}
      POSTGRES_PASSWORD: ${RATING_DB_PASSWORD}
    volumes:
      - rating_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  fx-db:
    build: ./db/fx
    container_name: quetxal-fx-db
    restart: always
    environment:
      POSTGRES_DB: ${FX_DB_NAME}
      POSTGRES_USER: ${FX_DB_USER}
      POSTGRES_PASSWORD: ${FX_DB_PASSWORD}
    volumes:
      - fx_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  history-db:
    build: ./db/history
    container_name: quetxal-history-db
    restart: always
    environment:
      POSTGRES_DB: ${HISTORY_DB_NAME}
      POSTGRES_USER: ${HISTORY_DB_USER}
      POSTGRES_PASSWORD: ${HISTORY_DB_PASSWORD}
    volumes:
      - history_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  notification-db:
    build: ./db/notification
    container_name: quetxal-notification-db
    restart: always
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    volumes:
      - notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  redis:
    build: ./cache
    container_name: quetxal-redis
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [quetxal-net]

  auth-service:
    build: ./backend/auth-service
    container_name: quetxal-auth-service
    environment:
      GRPC_PORT: 50051
      AUTH_DB_HOST: auth-db        
      AUTH_DB_PORT_INTERNAL: 5432   
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      DB_SSLMODE: disable
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL_MIN: ${JWT_TTL_MIN:-60}
    ports:
      - "50051:50051"   
    depends_on:
      auth-db:
        condition: service_healthy
    networks: [quetxal-net]

  # API Gateway 
  api-gateway:
    build: ./backend/api-gateway
    container_name: quetxal-api-gateway
    environment:
      GATEWAY_PORT: 8080
      AUTH_SERVICE_ADDR: auth-service:50051
      COOKIE_SECURE: "false"       
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "8080:8080"   
    depends_on:
      - auth-service
    networks: [quetxal-net]


volumes:
  auth_data:
  subscription_data:
  catalog_data:
  rating_data:
  fx_data:
  history_data:
  notification_data:
  redis_data:

networks:
  quetxal-net:
    driver: bridge
