name: quetxal-tv-gateway

services:

  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.gateway
    container_name: quetxal-api-gateway
    restart: always
    ports:
      - "80:3000"    # HTTP
      - "443:3443"   # HTTPS (self-signed cert or real cert)
    environment:
      SERVICE_NAME: api-gateway
      NODE_ENV: production

      # Microservices internal hosts (VM2 internal IP)
      IDENTITY_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      IDENTITY_SERVICE_PORT: 50051

      HISTORY_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      HISTORY_SERVICE_PORT: 50052

      CATALOG_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      CATALOG_SERVICE_PORT: 50053

      RATING_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      RATING_SERVICE_PORT: 50054

      FX_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      FX_SERVICE_PORT: 50055

      BILLING_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      BILLING_SERVICE_PORT: 50056

      NOTIFICATION_SERVICE_HOST: ${SERVICES_HOST:-10.128.0.2}
      NOTIFICATION_SERVICE_PORT: 50057

      # Gateway config
      GRPC_PORT: 3000
      LOG_LEVEL: info
    networks: [quetxal-net]

networks:
  quetxal-net:
    driver: bridge
