@startuml Diagrama_Secuencia_Usuario_Invitado
title Diagrama de secuencia - Usuario Invitado

skinparam backgroundColor #1E1E1E
skinparam sequence {
    ArrowColor White
    LifeLineBorderColor White
    LifeLineBackgroundColor #7FA6D9
    ParticipantBorderColor White
    ParticipantBackgroundColor #7FA6D9
    ParticipantFontColor White
    ActorBorderColor White
    ActorFontColor White
    ActorBackgroundColor #1E1E1E
    DatabaseBorderColor White
    DatabaseBackgroundColor #8C8C8C
    DatabaseFontColor White
}
skinparam shadowing false
skinparam defaultFontColor White

actor "Usuario Invitado" as Usuario

participant "API Gateway" as Gateway
participant "Auth Service" as Auth

database "Auth DB" as UserDB

== Intento de Navegación ==

Usuario -> Gateway : Intenta acceder al catálogo o inicio
Gateway --> Usuario : 302 Redirect (Redirige a Login / Registro por falta de sesión)

== Registro de Usuario (CDU-N1-01) ==

Usuario -> Gateway : POST /auth/register (email, password, perfil inicial)
Gateway -> Auth : gRPC Registrar(email, password, nombre_perfil)

Auth -> UserDB : Insertar nuevo usuario
Auth -> UserDB : Insertar perfil inicial
UserDB --> Auth : Retorna usuario_id y perfil_id

Auth --> Gateway : RegistrarResponse
Gateway --> Usuario : 201 Created (Registro exitoso, pide iniciar sesión)

@enduml
