// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/history.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerfilId      string                 `protobuf:"bytes,1,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Temporada     int32                  `protobuf:"varint,4,opt,name=temporada,proto3" json:"temporada,omitempty"`
	Episodio      int32                  `protobuf:"varint,5,opt,name=episodio,proto3" json:"episodio,omitempty"`
	SegundoExacto int32                  `protobuf:"varint,6,opt,name=segundo_exacto,json=segundoExacto,proto3" json:"segundo_exacto,omitempty"`
	DuracionTotal int32                  `protobuf:"varint,7,opt,name=duracion_total,json=duracionTotal,proto3" json:"duracion_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProgressRequest) Reset() {
	*x = SaveProgressRequest{}
	mi := &file_proto_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProgressRequest) ProtoMessage() {}

func (x *SaveProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProgressRequest.ProtoReflect.Descriptor instead.
func (*SaveProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{0}
}

func (x *SaveProgressRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *SaveProgressRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *SaveProgressRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *SaveProgressRequest) GetTemporada() int32 {
	if x != nil {
		return x.Temporada
	}
	return 0
}

func (x *SaveProgressRequest) GetEpisodio() int32 {
	if x != nil {
		return x.Episodio
	}
	return 0
}

func (x *SaveProgressRequest) GetSegundoExacto() int32 {
	if x != nil {
		return x.SegundoExacto
	}
	return 0
}

func (x *SaveProgressRequest) GetDuracionTotal() int32 {
	if x != nil {
		return x.DuracionTotal
	}
	return 0
}

type SaveProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProgressResponse) Reset() {
	*x = SaveProgressResponse{}
	mi := &file_proto_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProgressResponse) ProtoMessage() {}

func (x *SaveProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProgressResponse.ProtoReflect.Descriptor instead.
func (*SaveProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{1}
}

func (x *SaveProgressResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerfilId      string                 `protobuf:"bytes,1,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

type GetResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerfilId      string                 `protobuf:"bytes,1,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	mi := &file_proto_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{3}
}

func (x *GetResumeRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *GetResumeRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Historial     []*HistoryItem         `protobuf:"bytes,1,rep,name=historial,proto3" json:"historial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetHistorial() []*HistoryItem {
	if x != nil {
		return x.Historial
	}
	return nil
}

type HistoryItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PerfilId        string                 `protobuf:"bytes,2,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	ContenidoId     string                 `protobuf:"bytes,3,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Tipo            string                 `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Temporada       int32                  `protobuf:"varint,5,opt,name=temporada,proto3" json:"temporada,omitempty"`
	Episodio        int32                  `protobuf:"varint,6,opt,name=episodio,proto3" json:"episodio,omitempty"`
	SegundoExacto   int32                  `protobuf:"varint,7,opt,name=segundo_exacto,json=segundoExacto,proto3" json:"segundo_exacto,omitempty"`
	DuracionTotal   int32                  `protobuf:"varint,8,opt,name=duracion_total,json=duracionTotal,proto3" json:"duracion_total,omitempty"`
	PorcentajeVisto float64                `protobuf:"fixed64,9,opt,name=porcentaje_visto,json=porcentajeVisto,proto3" json:"porcentaje_visto,omitempty"`
	ActualizadoEn   string                 `protobuf:"bytes,10,opt,name=actualizado_en,json=actualizadoEn,proto3" json:"actualizado_en,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HistoryItem) Reset() {
	*x = HistoryItem{}
	mi := &file_proto_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryItem) ProtoMessage() {}

func (x *HistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryItem.ProtoReflect.Descriptor instead.
func (*HistoryItem) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoryItem) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *HistoryItem) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *HistoryItem) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *HistoryItem) GetTemporada() int32 {
	if x != nil {
		return x.Temporada
	}
	return 0
}

func (x *HistoryItem) GetEpisodio() int32 {
	if x != nil {
		return x.Episodio
	}
	return 0
}

func (x *HistoryItem) GetSegundoExacto() int32 {
	if x != nil {
		return x.SegundoExacto
	}
	return 0
}

func (x *HistoryItem) GetDuracionTotal() int32 {
	if x != nil {
		return x.DuracionTotal
	}
	return 0
}

func (x *HistoryItem) GetPorcentajeVisto() float64 {
	if x != nil {
		return x.PorcentajeVisto
	}
	return 0
}

func (x *HistoryItem) GetActualizadoEn() string {
	if x != nil {
		return x.ActualizadoEn
	}
	return ""
}

var File_proto_history_proto protoreflect.FileDescriptor

const file_proto_history_proto_rawDesc = "" +
	"\n" +
	"\x13proto/history.proto\x12\ahistory\"\xf1\x01\n" +
	"\x13SaveProgressRequest\x12\x1b\n" +
	"\tperfil_id\x18\x01 \x01(\tR\bperfilId\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x1c\n" +
	"\ttemporada\x18\x04 \x01(\x05R\ttemporada\x12\x1a\n" +
	"\bepisodio\x18\x05 \x01(\x05R\bepisodio\x12%\n" +
	"\x0esegundo_exacto\x18\x06 \x01(\x05R\rsegundoExacto\x12%\n" +
	"\x0eduracion_total\x18\a \x01(\x05R\rduracionTotal\"0\n" +
	"\x14SaveProgressResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"0\n" +
	"\x11GetHistoryRequest\x12\x1b\n" +
	"\tperfil_id\x18\x01 \x01(\tR\bperfilId\"R\n" +
	"\x10GetResumeRequest\x12\x1b\n" +
	"\tperfil_id\x18\x01 \x01(\tR\bperfilId\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId\"H\n" +
	"\x12GetHistoryResponse\x122\n" +
	"\thistorial\x18\x01 \x03(\v2\x14.history.HistoryItemR\thistorial\"\xcb\x02\n" +
	"\vHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperfil_id\x18\x02 \x01(\tR\bperfilId\x12!\n" +
	"\fcontenido_id\x18\x03 \x01(\tR\vcontenidoId\x12\x12\n" +
	"\x04tipo\x18\x04 \x01(\tR\x04tipo\x12\x1c\n" +
	"\ttemporada\x18\x05 \x01(\x05R\ttemporada\x12\x1a\n" +
	"\bepisodio\x18\x06 \x01(\x05R\bepisodio\x12%\n" +
	"\x0esegundo_exacto\x18\a \x01(\x05R\rsegundoExacto\x12%\n" +
	"\x0eduracion_total\x18\b \x01(\x05R\rduracionTotal\x12)\n" +
	"\x10porcentaje_visto\x18\t \x01(\x01R\x0fporcentajeVisto\x12%\n" +
	"\x0eactualizado_en\x18\n" +
	" \x01(\tR\ractualizadoEn2\xe2\x01\n" +
	"\x0eHistoryService\x12K\n" +
	"\fSaveProgress\x12\x1c.history.SaveProgressRequest\x1a\x1d.history.SaveProgressResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.history.GetHistoryRequest\x1a\x1b.history.GetHistoryResponse\x12<\n" +
	"\tGetResume\x12\x19.history.GetResumeRequest\x1a\x14.history.HistoryItemB1Z/github.com/grupo4/quetxaltv-gateway/internal/pbb\x06proto3"

var (
	file_proto_history_proto_rawDescOnce sync.Once
	file_proto_history_proto_rawDescData []byte
)

func file_proto_history_proto_rawDescGZIP() []byte {
	file_proto_history_proto_rawDescOnce.Do(func() {
		file_proto_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_history_proto_rawDesc), len(file_proto_history_proto_rawDesc)))
	})
	return file_proto_history_proto_rawDescData
}

var file_proto_history_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_history_proto_goTypes = []any{
	(*SaveProgressRequest)(nil),  // 0: history.SaveProgressRequest
	(*SaveProgressResponse)(nil), // 1: history.SaveProgressResponse
	(*GetHistoryRequest)(nil),    // 2: history.GetHistoryRequest
	(*GetResumeRequest)(nil),     // 3: history.GetResumeRequest
	(*GetHistoryResponse)(nil),   // 4: history.GetHistoryResponse
	(*HistoryItem)(nil),          // 5: history.HistoryItem
}
var file_proto_history_proto_depIdxs = []int32{
	5, // 0: history.GetHistoryResponse.historial:type_name -> history.HistoryItem
	0, // 1: history.HistoryService.SaveProgress:input_type -> history.SaveProgressRequest
	2, // 2: history.HistoryService.GetHistory:input_type -> history.GetHistoryRequest
	3, // 3: history.HistoryService.GetResume:input_type -> history.GetResumeRequest
	1, // 4: history.HistoryService.SaveProgress:output_type -> history.SaveProgressResponse
	4, // 5: history.HistoryService.GetHistory:output_type -> history.GetHistoryResponse
	5, // 6: history.HistoryService.GetResume:output_type -> history.HistoryItem
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_history_proto_init() }
func file_proto_history_proto_init() {
	if File_proto_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_history_proto_rawDesc), len(file_proto_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_history_proto_goTypes,
		DependencyIndexes: file_proto_history_proto_depIdxs,
		MessageInfos:      file_proto_history_proto_msgTypes,
	}.Build()
	File_proto_history_proto = out.File
	file_proto_history_proto_goTypes = nil
	file_proto_history_proto_depIdxs = nil
}
