# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66x.proto\x12\x05\x66x.v1\"U\n\x15\x43onvertirMontoRequest\x12\r\n\x05monto\x18\x01 \x01(\x01\x12\x15\n\rmoneda_origen\x18\x02 \x01(\t\x12\x16\n\x0emoneda_destino\x18\x03 \x01(\t\"y\n\x16\x43onvertirMontoResponse\x12\x16\n\x0emonto_original\x18\x01 \x01(\x01\x12\x18\n\x10monto_convertido\x18\x02 \x01(\x01\x12\x15\n\rmoneda_origen\x18\x03 \x01(\t\x12\x16\n\x0emoneda_destino\x18\x04 \x01(\t\"E\n\x14\x43onsultarTasaRequest\x12\x15\n\rmoneda_origen\x18\x01 \x01(\t\x12\x16\n\x0emoneda_destino\x18\x02 \x01(\t\"i\n\x15\x43onsultarTasaResponse\x12\x0c\n\x04tasa\x18\x01 \x01(\x01\x12\x15\n\rmoneda_origen\x18\x02 \x01(\t\x12\x16\n\x0emoneda_destino\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65sde_cache\x18\x04 \x01(\x08\x32\xa6\x01\n\tFXService\x12M\n\x0e\x43onvertirMonto\x12\x1c.fx.v1.ConvertirMontoRequest\x1a\x1d.fx.v1.ConvertirMontoResponse\x12J\n\rConsultarTasa\x12\x1b.fx.v1.ConsultarTasaRequest\x1a\x1c.fx.v1.ConsultarTasaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTIRMONTOREQUEST']._serialized_start=19
  _globals['_CONVERTIRMONTOREQUEST']._serialized_end=104
  _globals['_CONVERTIRMONTORESPONSE']._serialized_start=106
  _globals['_CONVERTIRMONTORESPONSE']._serialized_end=227
  _globals['_CONSULTARTASAREQUEST']._serialized_start=229
  _globals['_CONSULTARTASAREQUEST']._serialized_end=298
  _globals['_CONSULTARTASARESPONSE']._serialized_start=300
  _globals['_CONSULTARTASARESPONSE']._serialized_end=405
  _globals['_FXSERVICE']._serialized_start=408
  _globals['_FXSERVICE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
