# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import fx_pb2 as fx__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FXServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertirMonto = channel.unary_unary(
                '/fx.v1.FXService/ConvertirMonto',
                request_serializer=fx__pb2.ConvertirMontoRequest.SerializeToString,
                response_deserializer=fx__pb2.ConvertirMontoResponse.FromString,
                _registered_method=True)
        self.ConsultarTasa = channel.unary_unary(
                '/fx.v1.FXService/ConsultarTasa',
                request_serializer=fx__pb2.ConsultarTasaRequest.SerializeToString,
                response_deserializer=fx__pb2.ConsultarTasaResponse.FromString,
                _registered_method=True)


class FXServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ConvertirMonto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarTasa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FXServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertirMonto': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertirMonto,
                    request_deserializer=fx__pb2.ConvertirMontoRequest.FromString,
                    response_serializer=fx__pb2.ConvertirMontoResponse.SerializeToString,
            ),
            'ConsultarTasa': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarTasa,
                    request_deserializer=fx__pb2.ConsultarTasaRequest.FromString,
                    response_serializer=fx__pb2.ConsultarTasaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fx.v1.FXService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fx.v1.FXService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FXService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertirMonto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.v1.FXService/ConvertirMonto',
            fx__pb2.ConvertirMontoRequest.SerializeToString,
            fx__pb2.ConvertirMontoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarTasa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.v1.FXService/ConsultarTasa',
            fx__pb2.ConsultarTasaRequest.SerializeToString,
            fx__pb2.ConsultarTasaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
