// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Registrar_FullMethodName        = "/auth.v1.AuthService/Registrar"
	AuthService_Login_FullMethodName            = "/auth.v1.AuthService/Login"
	AuthService_ValidarToken_FullMethodName     = "/auth.v1.AuthService/ValidarToken"
	AuthService_CrearPerfil_FullMethodName      = "/auth.v1.AuthService/CrearPerfil"
	AuthService_EditarPerfil_FullMethodName     = "/auth.v1.AuthService/EditarPerfil"
	AuthService_ListarPerfiles_FullMethodName   = "/auth.v1.AuthService/ListarPerfiles"
	AuthService_ActualizarPerfil_FullMethodName = "/auth.v1.AuthService/ActualizarPerfil"
	AuthService_EliminarPerfil_FullMethodName   = "/auth.v1.AuthService/EliminarPerfil"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio de Identidad. Lo consume el API Gateway (unico punto de
// entrada) y otros microservicios para validar la identidad.
type AuthServiceClient interface {
	// Registro de una cuenta + su primer perfil (transaccion atomica).
	Registrar(ctx context.Context, in *RegistrarRequest, opts ...grpc.CallOption) (*RegistrarResponse, error)
	// Inicio de sesion local (email + password) -> devuelve un JWT.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Valida un JWT y propaga la identidad (lo usan los demas servicios).
	ValidarToken(ctx context.Context, in *ValidarTokenRequest, opts ...grpc.CallOption) (*ValidarTokenResponse, error)
	// Gestion de multiperfil (maximo 5 por cuenta).
	CrearPerfil(ctx context.Context, in *CrearPerfilRequest, opts ...grpc.CallOption) (*PerfilResponse, error)
	EditarPerfil(ctx context.Context, in *EditarPerfilRequest, opts ...grpc.CallOption) (*PerfilResponse, error)
	ListarPerfiles(ctx context.Context, in *ListarPerfilesRequest, opts ...grpc.CallOption) (*ListarPerfilesResponse, error)
	ActualizarPerfil(ctx context.Context, in *ActualizarPerfilRequest, opts ...grpc.CallOption) (*PerfilResponse, error)
	EliminarPerfil(ctx context.Context, in *EliminarPerfilRequest, opts ...grpc.CallOption) (*EliminarPerfilResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Registrar(ctx context.Context, in *RegistrarRequest, opts ...grpc.CallOption) (*RegistrarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrarResponse)
	err := c.cc.Invoke(ctx, AuthService_Registrar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidarToken(ctx context.Context, in *ValidarTokenRequest, opts ...grpc.CallOption) (*ValidarTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidarTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidarToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CrearPerfil(ctx context.Context, in *CrearPerfilRequest, opts ...grpc.CallOption) (*PerfilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerfilResponse)
	err := c.cc.Invoke(ctx, AuthService_CrearPerfil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) EditarPerfil(ctx context.Context, in *EditarPerfilRequest, opts ...grpc.CallOption) (*PerfilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerfilResponse)
	err := c.cc.Invoke(ctx, AuthService_EditarPerfil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListarPerfiles(ctx context.Context, in *ListarPerfilesRequest, opts ...grpc.CallOption) (*ListarPerfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarPerfilesResponse)
	err := c.cc.Invoke(ctx, AuthService_ListarPerfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ActualizarPerfil(ctx context.Context, in *ActualizarPerfilRequest, opts ...grpc.CallOption) (*PerfilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerfilResponse)
	err := c.cc.Invoke(ctx, AuthService_ActualizarPerfil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) EliminarPerfil(ctx context.Context, in *EliminarPerfilRequest, opts ...grpc.CallOption) (*EliminarPerfilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarPerfilResponse)
	err := c.cc.Invoke(ctx, AuthService_EliminarPerfil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// Servicio de Identidad. Lo consume el API Gateway (unico punto de
// entrada) y otros microservicios para validar la identidad.
type AuthServiceServer interface {
	// Registro de una cuenta + su primer perfil (transaccion atomica).
	Registrar(context.Context, *RegistrarRequest) (*RegistrarResponse, error)
	// Inicio de sesion local (email + password) -> devuelve un JWT.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Valida un JWT y propaga la identidad (lo usan los demas servicios).
	ValidarToken(context.Context, *ValidarTokenRequest) (*ValidarTokenResponse, error)
	// Gestion de multiperfil (maximo 5 por cuenta).
	CrearPerfil(context.Context, *CrearPerfilRequest) (*PerfilResponse, error)
	EditarPerfil(context.Context, *EditarPerfilRequest) (*PerfilResponse, error)
	ListarPerfiles(context.Context, *ListarPerfilesRequest) (*ListarPerfilesResponse, error)
	ActualizarPerfil(context.Context, *ActualizarPerfilRequest) (*PerfilResponse, error)
	EliminarPerfil(context.Context, *EliminarPerfilRequest) (*EliminarPerfilResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Registrar(context.Context, *RegistrarRequest) (*RegistrarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Registrar not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) ValidarToken(context.Context, *ValidarTokenRequest) (*ValidarTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidarToken not implemented")
}
func (UnimplementedAuthServiceServer) CrearPerfil(context.Context, *CrearPerfilRequest) (*PerfilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearPerfil not implemented")
}
func (UnimplementedAuthServiceServer) EditarPerfil(context.Context, *EditarPerfilRequest) (*PerfilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditarPerfil not implemented")
}
func (UnimplementedAuthServiceServer) ListarPerfiles(context.Context, *ListarPerfilesRequest) (*ListarPerfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarPerfiles not implemented")
}
func (UnimplementedAuthServiceServer) ActualizarPerfil(context.Context, *ActualizarPerfilRequest) (*PerfilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarPerfil not implemented")
}
func (UnimplementedAuthServiceServer) EliminarPerfil(context.Context, *EliminarPerfilRequest) (*EliminarPerfilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarPerfil not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Registrar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Registrar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Registrar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Registrar(ctx, req.(*RegistrarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidarToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidarTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidarToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidarToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidarToken(ctx, req.(*ValidarTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CrearPerfil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearPerfilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CrearPerfil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CrearPerfil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CrearPerfil(ctx, req.(*CrearPerfilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_EditarPerfil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditarPerfilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).EditarPerfil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_EditarPerfil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).EditarPerfil(ctx, req.(*EditarPerfilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListarPerfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarPerfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListarPerfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListarPerfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListarPerfiles(ctx, req.(*ListarPerfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ActualizarPerfil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarPerfilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ActualizarPerfil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ActualizarPerfil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ActualizarPerfil(ctx, req.(*ActualizarPerfilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_EliminarPerfil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarPerfilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).EliminarPerfil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_EliminarPerfil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).EliminarPerfil(ctx, req.(*EliminarPerfilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registrar",
			Handler:    _AuthService_Registrar_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "ValidarToken",
			Handler:    _AuthService_ValidarToken_Handler,
		},
		{
			MethodName: "CrearPerfil",
			Handler:    _AuthService_CrearPerfil_Handler,
		},
		{
			MethodName: "EditarPerfil",
			Handler:    _AuthService_EditarPerfil_Handler,
		},
		{
			MethodName: "ListarPerfiles",
			Handler:    _AuthService_ListarPerfiles_Handler,
		},
		{
			MethodName: "ActualizarPerfil",
			Handler:    _AuthService_ActualizarPerfil_Handler,
		},
		{
			MethodName: "EliminarPerfil",
			Handler:    _AuthService_EliminarPerfil_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
