// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NombrePerfil  string                 `protobuf:"bytes,3,opt,name=nombre_perfil,json=nombrePerfil,proto3" json:"nombre_perfil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrarRequest) Reset() {
	*x = RegistrarRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarRequest) ProtoMessage() {}

func (x *RegistrarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarRequest.ProtoReflect.Descriptor instead.
func (*RegistrarRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrarRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrarRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrarRequest) GetNombrePerfil() string {
	if x != nil {
		return x.NombrePerfil
	}
	return ""
}

type RegistrarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	PerfilId      string                 `protobuf:"bytes,2,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrarResponse) Reset() {
	*x = RegistrarResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarResponse) ProtoMessage() {}

func (x *RegistrarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarResponse.ProtoReflect.Descriptor instead.
func (*RegistrarResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrarResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *RegistrarResponse) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UsuarioId     string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	ExpiraEn      int64                  `protobuf:"varint,3,opt,name=expira_en,json=expiraEn,proto3" json:"expira_en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *LoginResponse) GetExpiraEn() int64 {
	if x != nil {
		return x.ExpiraEn
	}
	return 0
}

type ValidarTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarTokenRequest) Reset() {
	*x = ValidarTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenRequest) ProtoMessage() {}

func (x *ValidarTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidarTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ValidarTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidarTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valido        bool                   `protobuf:"varint,1,opt,name=valido,proto3" json:"valido,omitempty"`
	UsuarioId     string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Rol           string                 `protobuf:"bytes,3,opt,name=rol,proto3" json:"rol,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarTokenResponse) Reset() {
	*x = ValidarTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenResponse) ProtoMessage() {}

func (x *ValidarTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidarTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidarTokenResponse) GetValido() bool {
	if x != nil {
		return x.Valido
	}
	return false
}

func (x *ValidarTokenResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ValidarTokenResponse) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

func (x *ValidarTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CrearPerfilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	EsInfantil    bool                   `protobuf:"varint,3,opt,name=es_infantil,json=esInfantil,proto3" json:"es_infantil,omitempty"`
	Idioma        string                 `protobuf:"bytes,4,opt,name=idioma,proto3" json:"idioma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPerfilRequest) Reset() {
	*x = CrearPerfilRequest{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPerfilRequest) ProtoMessage() {}

func (x *CrearPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPerfilRequest.ProtoReflect.Descriptor instead.
func (*CrearPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CrearPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *CrearPerfilRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CrearPerfilRequest) GetEsInfantil() bool {
	if x != nil {
		return x.EsInfantil
	}
	return false
}

func (x *CrearPerfilRequest) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

type PerfilResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	EsInfantil    bool                   `protobuf:"varint,3,opt,name=es_infantil,json=esInfantil,proto3" json:"es_infantil,omitempty"`
	Idioma        string                 `protobuf:"bytes,4,opt,name=idioma,proto3" json:"idioma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerfilResponse) Reset() {
	*x = PerfilResponse{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfilResponse) ProtoMessage() {}

func (x *PerfilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfilResponse.ProtoReflect.Descriptor instead.
func (*PerfilResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *PerfilResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PerfilResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PerfilResponse) GetEsInfantil() bool {
	if x != nil {
		return x.EsInfantil
	}
	return false
}

func (x *PerfilResponse) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

type ListarPerfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarPerfilesRequest) Reset() {
	*x = ListarPerfilesRequest{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarPerfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPerfilesRequest) ProtoMessage() {}

func (x *ListarPerfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPerfilesRequest.ProtoReflect.Descriptor instead.
func (*ListarPerfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ListarPerfilesRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type ListarPerfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perfiles      []*PerfilResponse      `protobuf:"bytes,1,rep,name=perfiles,proto3" json:"perfiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarPerfilesResponse) Reset() {
	*x = ListarPerfilesResponse{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarPerfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPerfilesResponse) ProtoMessage() {}

func (x *ListarPerfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPerfilesResponse.ProtoReflect.Descriptor instead.
func (*ListarPerfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ListarPerfilesResponse) GetPerfiles() []*PerfilResponse {
	if x != nil {
		return x.Perfiles
	}
	return nil
}

type ActualizarPerfilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsuarioId     string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarPerfilRequest) Reset() {
	*x = ActualizarPerfilRequest{}
	mi := &file_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarPerfilRequest) ProtoMessage() {}

func (x *ActualizarPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarPerfilRequest.ProtoReflect.Descriptor instead.
func (*ActualizarPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ActualizarPerfilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ActualizarPerfilRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type EliminarPerfilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsuarioId     string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarPerfilRequest) Reset() {
	*x = EliminarPerfilRequest{}
	mi := &file_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarPerfilRequest) ProtoMessage() {}

func (x *EliminarPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarPerfilRequest.ProtoReflect.Descriptor instead.
func (*EliminarPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *EliminarPerfilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EliminarPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type EliminarPerfilResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarPerfilResponse) Reset() {
	*x = EliminarPerfilResponse{}
	mi := &file_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarPerfilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarPerfilResponse) ProtoMessage() {}

func (x *EliminarPerfilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarPerfilResponse.ProtoReflect.Descriptor instead.
func (*EliminarPerfilResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *EliminarPerfilResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\aauth.v1\"i\n" +
	"\x10RegistrarRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rnombre_perfil\x18\x03 \x01(\tR\fnombrePerfil\"O\n" +
	"\x11RegistrarResponse\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x1b\n" +
	"\tperfil_id\x18\x02 \x01(\tR\bperfilId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"n\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\x12\x1b\n" +
	"\texpira_en\x18\x03 \x01(\x03R\bexpiraEn\"+\n" +
	"\x13ValidarTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"u\n" +
	"\x14ValidarTokenResponse\x12\x16\n" +
	"\x06valido\x18\x01 \x01(\bR\x06valido\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\x12\x10\n" +
	"\x03rol\x18\x03 \x01(\tR\x03rol\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x84\x01\n" +
	"\x12CrearPerfilRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1f\n" +
	"\ves_infantil\x18\x03 \x01(\bR\n" +
	"esInfantil\x12\x16\n" +
	"\x06idioma\x18\x04 \x01(\tR\x06idioma\"q\n" +
	"\x0ePerfilResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1f\n" +
	"\ves_infantil\x18\x03 \x01(\bR\n" +
	"esInfantil\x12\x16\n" +
	"\x06idioma\x18\x04 \x01(\tR\x06idioma\"6\n" +
	"\x15ListarPerfilesRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\"M\n" +
	"\x16ListarPerfilesResponse\x123\n" +
	"\bperfiles\x18\x01 \x03(\v2\x17.auth.v1.PerfilResponseR\bperfiles\"`\n" +
	"\x17ActualizarPerfilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\x12\x16\n" +
	"\x06nombre\x18\x03 \x01(\tR\x06nombre\"F\n" +
	"\x15EliminarPerfilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\"2\n" +
	"\x16EliminarPerfilResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x90\x04\n" +
	"\vAuthService\x12B\n" +
	"\tRegistrar\x12\x19.auth.v1.RegistrarRequest\x1a\x1a.auth.v1.RegistrarResponse\x126\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12K\n" +
	"\fValidarToken\x12\x1c.auth.v1.ValidarTokenRequest\x1a\x1d.auth.v1.ValidarTokenResponse\x12C\n" +
	"\vCrearPerfil\x12\x1b.auth.v1.CrearPerfilRequest\x1a\x17.auth.v1.PerfilResponse\x12Q\n" +
	"\x0eListarPerfiles\x12\x1e.auth.v1.ListarPerfilesRequest\x1a\x1f.auth.v1.ListarPerfilesResponse\x12M\n" +
	"\x10ActualizarPerfil\x12 .auth.v1.ActualizarPerfilRequest\x1a\x17.auth.v1.PerfilResponse\x12Q\n" +
	"\x0eEliminarPerfil\x12\x1e.auth.v1.EliminarPerfilRequest\x1a\x1f.auth.v1.EliminarPerfilResponseB4Z2github.com/grupo4/quetxaltv-gateway/internal/pb;pbb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_auth_proto_goTypes = []any{
	(*RegistrarRequest)(nil),        // 0: auth.v1.RegistrarRequest
	(*RegistrarResponse)(nil),       // 1: auth.v1.RegistrarResponse
	(*LoginRequest)(nil),            // 2: auth.v1.LoginRequest
	(*LoginResponse)(nil),           // 3: auth.v1.LoginResponse
	(*ValidarTokenRequest)(nil),     // 4: auth.v1.ValidarTokenRequest
	(*ValidarTokenResponse)(nil),    // 5: auth.v1.ValidarTokenResponse
	(*CrearPerfilRequest)(nil),      // 6: auth.v1.CrearPerfilRequest
	(*PerfilResponse)(nil),          // 7: auth.v1.PerfilResponse
	(*ListarPerfilesRequest)(nil),   // 8: auth.v1.ListarPerfilesRequest
	(*ListarPerfilesResponse)(nil),  // 9: auth.v1.ListarPerfilesResponse
	(*ActualizarPerfilRequest)(nil), // 10: auth.v1.ActualizarPerfilRequest
	(*EliminarPerfilRequest)(nil),   // 11: auth.v1.EliminarPerfilRequest
	(*EliminarPerfilResponse)(nil),  // 12: auth.v1.EliminarPerfilResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	7,  // 0: auth.v1.ListarPerfilesResponse.perfiles:type_name -> auth.v1.PerfilResponse
	0,  // 1: auth.v1.AuthService.Registrar:input_type -> auth.v1.RegistrarRequest
	2,  // 2: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	4,  // 3: auth.v1.AuthService.ValidarToken:input_type -> auth.v1.ValidarTokenRequest
	6,  // 4: auth.v1.AuthService.CrearPerfil:input_type -> auth.v1.CrearPerfilRequest
	8,  // 5: auth.v1.AuthService.ListarPerfiles:input_type -> auth.v1.ListarPerfilesRequest
	10, // 6: auth.v1.AuthService.ActualizarPerfil:input_type -> auth.v1.ActualizarPerfilRequest
	11, // 7: auth.v1.AuthService.EliminarPerfil:input_type -> auth.v1.EliminarPerfilRequest
	1,  // 8: auth.v1.AuthService.Registrar:output_type -> auth.v1.RegistrarResponse
	3,  // 9: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	5,  // 10: auth.v1.AuthService.ValidarToken:output_type -> auth.v1.ValidarTokenResponse
	7,  // 11: auth.v1.AuthService.CrearPerfil:output_type -> auth.v1.PerfilResponse
	9,  // 12: auth.v1.AuthService.ListarPerfiles:output_type -> auth.v1.ListarPerfilesResponse
	7,  // 13: auth.v1.AuthService.ActualizarPerfil:output_type -> auth.v1.PerfilResponse
	12, // 14: auth.v1.AuthService.EliminarPerfil:output_type -> auth.v1.EliminarPerfilResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
