// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NombrePlan    string                 `protobuf:"bytes,2,opt,name=nombre_plan,json=nombrePlan,proto3" json:"nombre_plan,omitempty"`
	PrecioBase    float64                `protobuf:"fixed64,3,opt,name=precio_base,json=precioBase,proto3" json:"precio_base,omitempty"`
	MonedaBase    string                 `protobuf:"bytes,4,opt,name=moneda_base,json=monedaBase,proto3" json:"moneda_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_proto_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetNombrePlan() string {
	if x != nil {
		return x.NombrePlan
	}
	return ""
}

func (x *Plan) GetPrecioBase() float64 {
	if x != nil {
		return x.PrecioBase
	}
	return 0
}

func (x *Plan) GetMonedaBase() string {
	if x != nil {
		return x.MonedaBase
	}
	return ""
}

type GetPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Planes        []*Plan                `protobuf:"bytes,1,rep,name=planes,proto3" json:"planes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlansResponse) Reset() {
	*x = GetPlansResponse{}
	mi := &file_proto_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlansResponse) ProtoMessage() {}

func (x *GetPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlansResponse.ProtoReflect.Descriptor instead.
func (*GetPlansResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlansResponse) GetPlanes() []*Plan {
	if x != nil {
		return x.Planes
	}
	return nil
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Monto         float64                `protobuf:"fixed64,3,opt,name=monto,proto3" json:"monto,omitempty"`
	Moneda        string                 `protobuf:"bytes,4,opt,name=moneda,proto3" json:"moneda,omitempty"`
	Meses         int32                  `protobuf:"varint,5,opt,name=meses,proto3" json:"meses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_proto_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSubscriptionRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetMonto() float64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetMeses() int32 {
	if x != nil {
		return x.Meses
	}
	return 0
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuscripcionId string                 `protobuf:"bytes,1,opt,name=suscripcion_id,json=suscripcionId,proto3" json:"suscripcion_id,omitempty"`
	PagoId        string                 `protobuf:"bytes,2,opt,name=pago_id,json=pagoId,proto3" json:"pago_id,omitempty"`
	Mensaje       string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_proto_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSubscriptionResponse) GetSuscripcionId() string {
	if x != nil {
		return x.SuscripcionId
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetPagoId() string {
	if x != nil {
		return x.PagoId
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_proto_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSubscriptionRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type GetUserSubscriptionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SuscripcionId     string                 `protobuf:"bytes,1,opt,name=suscripcion_id,json=suscripcionId,proto3" json:"suscripcion_id,omitempty"`
	UsuarioId         string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	PlanId            string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	NombrePlan        string                 `protobuf:"bytes,4,opt,name=nombre_plan,json=nombrePlan,proto3" json:"nombre_plan,omitempty"`
	EstadoSuscripcion string                 `protobuf:"bytes,5,opt,name=estado_suscripcion,json=estadoSuscripcion,proto3" json:"estado_suscripcion,omitempty"`
	FechaInicio       string                 `protobuf:"bytes,6,opt,name=fecha_inicio,json=fechaInicio,proto3" json:"fecha_inicio,omitempty"`
	FechaFin          string                 `protobuf:"bytes,7,opt,name=fecha_fin,json=fechaFin,proto3" json:"fecha_fin,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserSubscriptionResponse) Reset() {
	*x = GetUserSubscriptionResponse{}
	mi := &file_proto_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionResponse) ProtoMessage() {}

func (x *GetUserSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSubscriptionResponse) GetSuscripcionId() string {
	if x != nil {
		return x.SuscripcionId
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetNombrePlan() string {
	if x != nil {
		return x.NombrePlan
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetEstadoSuscripcion() string {
	if x != nil {
		return x.EstadoSuscripcion
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetFechaInicio() string {
	if x != nil {
		return x.FechaInicio
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetFechaFin() string {
	if x != nil {
		return x.FechaFin
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_proto_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{7}
}

func (x *CancelSubscriptionRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuscripcionId string                 `protobuf:"bytes,1,opt,name=suscripcion_id,json=suscripcionId,proto3" json:"suscripcion_id,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_proto_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{8}
}

func (x *CancelSubscriptionResponse) GetSuscripcionId() string {
	if x != nil {
		return x.SuscripcionId
	}
	return ""
}

func (x *CancelSubscriptionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ChangeSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	NuevoPlanId   string                 `protobuf:"bytes,2,opt,name=nuevo_plan_id,json=nuevoPlanId,proto3" json:"nuevo_plan_id,omitempty"`
	Monto         float64                `protobuf:"fixed64,3,opt,name=monto,proto3" json:"monto,omitempty"`
	Moneda        string                 `protobuf:"bytes,4,opt,name=moneda,proto3" json:"moneda,omitempty"`
	Meses         int32                  `protobuf:"varint,5,opt,name=meses,proto3" json:"meses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSubscriptionRequest) Reset() {
	*x = ChangeSubscriptionRequest{}
	mi := &file_proto_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSubscriptionRequest) ProtoMessage() {}

func (x *ChangeSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ChangeSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeSubscriptionRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ChangeSubscriptionRequest) GetNuevoPlanId() string {
	if x != nil {
		return x.NuevoPlanId
	}
	return ""
}

func (x *ChangeSubscriptionRequest) GetMonto() float64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

func (x *ChangeSubscriptionRequest) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *ChangeSubscriptionRequest) GetMeses() int32 {
	if x != nil {
		return x.Meses
	}
	return 0
}

type ChangeSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuscripcionId string                 `protobuf:"bytes,1,opt,name=suscripcion_id,json=suscripcionId,proto3" json:"suscripcion_id,omitempty"`
	PagoId        string                 `protobuf:"bytes,2,opt,name=pago_id,json=pagoId,proto3" json:"pago_id,omitempty"`
	Mensaje       string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSubscriptionResponse) Reset() {
	*x = ChangeSubscriptionResponse{}
	mi := &file_proto_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSubscriptionResponse) ProtoMessage() {}

func (x *ChangeSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*ChangeSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeSubscriptionResponse) GetSuscripcionId() string {
	if x != nil {
		return x.SuscripcionId
	}
	return ""
}

func (x *ChangeSubscriptionResponse) GetPagoId() string {
	if x != nil {
		return x.PagoId
	}
	return ""
}

func (x *ChangeSubscriptionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_billing_proto protoreflect.FileDescriptor

const file_proto_billing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/billing.proto\x12\n" +
	"billing.v1\"\a\n" +
	"\x05Empty\"y\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vnombre_plan\x18\x02 \x01(\tR\n" +
	"nombrePlan\x12\x1f\n" +
	"\vprecio_base\x18\x03 \x01(\x01R\n" +
	"precioBase\x12\x1f\n" +
	"\vmoneda_base\x18\x04 \x01(\tR\n" +
	"monedaBase\"<\n" +
	"\x10GetPlansResponse\x12(\n" +
	"\x06planes\x18\x01 \x03(\v2\x10.billing.v1.PlanR\x06planes\"\x97\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x14\n" +
	"\x05monto\x18\x03 \x01(\x01R\x05monto\x12\x16\n" +
	"\x06moneda\x18\x04 \x01(\tR\x06moneda\x12\x14\n" +
	"\x05meses\x18\x05 \x01(\x05R\x05meses\"v\n" +
	"\x1aCreateSubscriptionResponse\x12%\n" +
	"\x0esuscripcion_id\x18\x01 \x01(\tR\rsuscripcionId\x12\x17\n" +
	"\apago_id\x18\x02 \x01(\tR\x06pagoId\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje\";\n" +
	"\x1aGetUserSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\"\x8c\x02\n" +
	"\x1bGetUserSubscriptionResponse\x12%\n" +
	"\x0esuscripcion_id\x18\x01 \x01(\tR\rsuscripcionId\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12\x1f\n" +
	"\vnombre_plan\x18\x04 \x01(\tR\n" +
	"nombrePlan\x12-\n" +
	"\x12estado_suscripcion\x18\x05 \x01(\tR\x11estadoSuscripcion\x12!\n" +
	"\ffecha_inicio\x18\x06 \x01(\tR\vfechaInicio\x12\x1b\n" +
	"\tfecha_fin\x18\a \x01(\tR\bfechaFin\":\n" +
	"\x19CancelSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\"]\n" +
	"\x1aCancelSubscriptionResponse\x12%\n" +
	"\x0esuscripcion_id\x18\x01 \x01(\tR\rsuscripcionId\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\xa2\x01\n" +
	"\x19ChangeSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\"\n" +
	"\rnuevo_plan_id\x18\x02 \x01(\tR\vnuevoPlanId\x12\x14\n" +
	"\x05monto\x18\x03 \x01(\x01R\x05monto\x12\x16\n" +
	"\x06moneda\x18\x04 \x01(\tR\x06moneda\x12\x14\n" +
	"\x05meses\x18\x05 \x01(\x05R\x05meses\"v\n" +
	"\x1aChangeSubscriptionResponse\x12%\n" +
	"\x0esuscripcion_id\x18\x01 \x01(\tR\rsuscripcionId\x12\x17\n" +
	"\apago_id\x18\x02 \x01(\tR\x06pagoId\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje2\xe4\x03\n" +
	"\x0eBillingService\x12;\n" +
	"\bGetPlans\x12\x11.billing.v1.Empty\x1a\x1c.billing.v1.GetPlansResponse\x12c\n" +
	"\x12CreateSubscription\x12%.billing.v1.CreateSubscriptionRequest\x1a&.billing.v1.CreateSubscriptionResponse\x12f\n" +
	"\x13GetUserSubscription\x12&.billing.v1.GetUserSubscriptionRequest\x1a'.billing.v1.GetUserSubscriptionResponse\x12c\n" +
	"\x12CancelSubscription\x12%.billing.v1.CancelSubscriptionRequest\x1a&.billing.v1.CancelSubscriptionResponse\x12c\n" +
	"\x12ChangeSubscription\x12%.billing.v1.ChangeSubscriptionRequest\x1a&.billing.v1.ChangeSubscriptionResponseB4Z2github.com/grupo4/quetxaltv-gateway/internal/pb;pbb\x06proto3"

var (
	file_proto_billing_proto_rawDescOnce sync.Once
	file_proto_billing_proto_rawDescData []byte
)

func file_proto_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)))
	})
	return file_proto_billing_proto_rawDescData
}

var file_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_billing_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: billing.v1.Empty
	(*Plan)(nil),                        // 1: billing.v1.Plan
	(*GetPlansResponse)(nil),            // 2: billing.v1.GetPlansResponse
	(*CreateSubscriptionRequest)(nil),   // 3: billing.v1.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),  // 4: billing.v1.CreateSubscriptionResponse
	(*GetUserSubscriptionRequest)(nil),  // 5: billing.v1.GetUserSubscriptionRequest
	(*GetUserSubscriptionResponse)(nil), // 6: billing.v1.GetUserSubscriptionResponse
	(*CancelSubscriptionRequest)(nil),   // 7: billing.v1.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil),  // 8: billing.v1.CancelSubscriptionResponse
	(*ChangeSubscriptionRequest)(nil),   // 9: billing.v1.ChangeSubscriptionRequest
	(*ChangeSubscriptionResponse)(nil),  // 10: billing.v1.ChangeSubscriptionResponse
}
var file_proto_billing_proto_depIdxs = []int32{
	1,  // 0: billing.v1.GetPlansResponse.planes:type_name -> billing.v1.Plan
	0,  // 1: billing.v1.BillingService.GetPlans:input_type -> billing.v1.Empty
	3,  // 2: billing.v1.BillingService.CreateSubscription:input_type -> billing.v1.CreateSubscriptionRequest
	5,  // 3: billing.v1.BillingService.GetUserSubscription:input_type -> billing.v1.GetUserSubscriptionRequest
	7,  // 4: billing.v1.BillingService.CancelSubscription:input_type -> billing.v1.CancelSubscriptionRequest
	9,  // 5: billing.v1.BillingService.ChangeSubscription:input_type -> billing.v1.ChangeSubscriptionRequest
	2,  // 6: billing.v1.BillingService.GetPlans:output_type -> billing.v1.GetPlansResponse
	4,  // 7: billing.v1.BillingService.CreateSubscription:output_type -> billing.v1.CreateSubscriptionResponse
	6,  // 8: billing.v1.BillingService.GetUserSubscription:output_type -> billing.v1.GetUserSubscriptionResponse
	8,  // 9: billing.v1.BillingService.CancelSubscription:output_type -> billing.v1.CancelSubscriptionResponse
	10, // 10: billing.v1.BillingService.ChangeSubscription:output_type -> billing.v1.ChangeSubscriptionResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_billing_proto_init() }
func file_proto_billing_proto_init() {
	if File_proto_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_proto = out.File
	file_proto_billing_proto_goTypes = nil
	file_proto_billing_proto_depIdxs = nil
}
