// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/catalog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CatalogService_ExplorarCartelera_FullMethodName      = "/catalog.v1.CatalogService/ExplorarCartelera"
	CatalogService_BuscarContenido_FullMethodName        = "/catalog.v1.CatalogService/BuscarContenido"
	CatalogService_ObtenerFichaTecnica_FullMethodName    = "/catalog.v1.CatalogService/ObtenerFichaTecnica"
	CatalogService_ObtenerRecomendaciones_FullMethodName = "/catalog.v1.CatalogService/ObtenerRecomendaciones"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	ExplorarCartelera(ctx context.Context, in *ExplorarCarteleraRequest, opts ...grpc.CallOption) (*CarteleraResponse, error)
	BuscarContenido(ctx context.Context, in *BuscarContenidoRequest, opts ...grpc.CallOption) (*CarteleraResponse, error)
	ObtenerFichaTecnica(ctx context.Context, in *FichaTecnicaRequest, opts ...grpc.CallOption) (*FichaTecnicaResponse, error)
	ObtenerRecomendaciones(ctx context.Context, in *ObtenerRecomendacionesRequest, opts ...grpc.CallOption) (*CarteleraResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ExplorarCartelera(ctx context.Context, in *ExplorarCarteleraRequest, opts ...grpc.CallOption) (*CarteleraResponse, error) {
	out := new(CarteleraResponse)
	err := c.cc.Invoke(ctx, CatalogService_ExplorarCartelera_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) BuscarContenido(ctx context.Context, in *BuscarContenidoRequest, opts ...grpc.CallOption) (*CarteleraResponse, error) {
	out := new(CarteleraResponse)
	err := c.cc.Invoke(ctx, CatalogService_BuscarContenido_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ObtenerFichaTecnica(ctx context.Context, in *FichaTecnicaRequest, opts ...grpc.CallOption) (*FichaTecnicaResponse, error) {
	out := new(FichaTecnicaResponse)
	err := c.cc.Invoke(ctx, CatalogService_ObtenerFichaTecnica_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ObtenerRecomendaciones(ctx context.Context, in *ObtenerRecomendacionesRequest, opts ...grpc.CallOption) (*CarteleraResponse, error) {
	out := new(CarteleraResponse)
	err := c.cc.Invoke(ctx, CatalogService_ObtenerRecomendaciones_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility
type CatalogServiceServer interface {
	ExplorarCartelera(context.Context, *ExplorarCarteleraRequest) (*CarteleraResponse, error)
	BuscarContenido(context.Context, *BuscarContenidoRequest) (*CarteleraResponse, error)
	ObtenerFichaTecnica(context.Context, *FichaTecnicaRequest) (*FichaTecnicaResponse, error)
	ObtenerRecomendaciones(context.Context, *ObtenerRecomendacionesRequest) (*CarteleraResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (UnimplementedCatalogServiceServer) ExplorarCartelera(context.Context, *ExplorarCarteleraRequest) (*CarteleraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplorarCartelera not implemented")
}
func (UnimplementedCatalogServiceServer) BuscarContenido(context.Context, *BuscarContenidoRequest) (*CarteleraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuscarContenido not implemented")
}
func (UnimplementedCatalogServiceServer) ObtenerFichaTecnica(context.Context, *FichaTecnicaRequest) (*FichaTecnicaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerFichaTecnica not implemented")
}
func (UnimplementedCatalogServiceServer) ObtenerRecomendaciones(context.Context, *ObtenerRecomendacionesRequest) (*CarteleraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerRecomendaciones not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ExplorarCartelera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplorarCarteleraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ExplorarCartelera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ExplorarCartelera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ExplorarCartelera(ctx, req.(*ExplorarCarteleraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_BuscarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuscarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).BuscarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_BuscarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).BuscarContenido(ctx, req.(*BuscarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ObtenerFichaTecnica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FichaTecnicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ObtenerFichaTecnica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ObtenerFichaTecnica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ObtenerFichaTecnica(ctx, req.(*FichaTecnicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ObtenerRecomendaciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerRecomendacionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ObtenerRecomendaciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ObtenerRecomendaciones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ObtenerRecomendaciones(ctx, req.(*ObtenerRecomendacionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExplorarCartelera",
			Handler:    _CatalogService_ExplorarCartelera_Handler,
		},
		{
			MethodName: "BuscarContenido",
			Handler:    _CatalogService_BuscarContenido_Handler,
		},
		{
			MethodName: "ObtenerFichaTecnica",
			Handler:    _CatalogService_ObtenerFichaTecnica_Handler,
		},
		{
			MethodName: "ObtenerRecomendaciones",
			Handler:    _CatalogService_ObtenerRecomendaciones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog.proto",
}
