// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/catalog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExplorarCarteleraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplorarCarteleraRequest) Reset() {
	*x = ExplorarCarteleraRequest{}
	mi := &file_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplorarCarteleraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplorarCarteleraRequest) ProtoMessage() {}

func (x *ExplorarCarteleraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplorarCarteleraRequest.ProtoReflect.Descriptor instead.
func (*ExplorarCarteleraRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{0}
}

type BuscarContenidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Categoria     string                 `protobuf:"bytes,2,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Genero        string                 `protobuf:"bytes,3,opt,name=genero,proto3" json:"genero,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Tipo          string                 `protobuf:"bytes,5,opt,name=tipo,proto3" json:"tipo,omitempty"` // 'pelicula' | 'serie', opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuscarContenidoRequest) Reset() {
	*x = BuscarContenidoRequest{}
	mi := &file_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuscarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarContenidoRequest) ProtoMessage() {}

func (x *BuscarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarContenidoRequest.ProtoReflect.Descriptor instead.
func (*BuscarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *BuscarContenidoRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *BuscarContenidoRequest) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *BuscarContenidoRequest) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *BuscarContenidoRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *BuscarContenidoRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type ItemCartelera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Anio          int32                  `protobuf:"varint,4,opt,name=anio,proto3" json:"anio,omitempty"`
	Clasificacion string                 `protobuf:"bytes,5,opt,name=clasificacion,proto3" json:"clasificacion,omitempty"`
	Generos       string                 `protobuf:"bytes,6,opt,name=generos,proto3" json:"generos,omitempty"`
	Categorias    string                 `protobuf:"bytes,7,opt,name=categorias,proto3" json:"categorias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCartelera) Reset() {
	*x = ItemCartelera{}
	mi := &file_proto_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCartelera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCartelera) ProtoMessage() {}

func (x *ItemCartelera) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCartelera.ProtoReflect.Descriptor instead.
func (*ItemCartelera) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ItemCartelera) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *ItemCartelera) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *ItemCartelera) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ItemCartelera) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *ItemCartelera) GetClasificacion() string {
	if x != nil {
		return x.Clasificacion
	}
	return ""
}

func (x *ItemCartelera) GetGeneros() string {
	if x != nil {
		return x.Generos
	}
	return ""
}

func (x *ItemCartelera) GetCategorias() string {
	if x != nil {
		return x.Categorias
	}
	return ""
}

type CarteleraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemCartelera       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarteleraResponse) Reset() {
	*x = CarteleraResponse{}
	mi := &file_proto_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarteleraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarteleraResponse) ProtoMessage() {}

func (x *CarteleraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarteleraResponse.ProtoReflect.Descriptor instead.
func (*CarteleraResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CarteleraResponse) GetItems() []*ItemCartelera {
	if x != nil {
		return x.Items
	}
	return nil
}

type FichaTecnicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FichaTecnicaRequest) Reset() {
	*x = FichaTecnicaRequest{}
	mi := &file_proto_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FichaTecnicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FichaTecnicaRequest) ProtoMessage() {}

func (x *FichaTecnicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FichaTecnicaRequest.ProtoReflect.Descriptor instead.
func (*FichaTecnicaRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *FichaTecnicaRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type MiembroReparto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Personaje     string                 `protobuf:"bytes,2,opt,name=personaje,proto3" json:"personaje,omitempty"`
	Rol           string                 `protobuf:"bytes,3,opt,name=rol,proto3" json:"rol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiembroReparto) Reset() {
	*x = MiembroReparto{}
	mi := &file_proto_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiembroReparto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiembroReparto) ProtoMessage() {}

func (x *MiembroReparto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiembroReparto.ProtoReflect.Descriptor instead.
func (*MiembroReparto) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *MiembroReparto) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *MiembroReparto) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

func (x *MiembroReparto) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

type Episodio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numero        int32                  `protobuf:"varint,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	DuracionMin   int32                  `protobuf:"varint,3,opt,name=duracion_min,json=duracionMin,proto3" json:"duracion_min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episodio) Reset() {
	*x = Episodio{}
	mi := &file_proto_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episodio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episodio) ProtoMessage() {}

func (x *Episodio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episodio.ProtoReflect.Descriptor instead.
func (*Episodio) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *Episodio) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *Episodio) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Episodio) GetDuracionMin() int32 {
	if x != nil {
		return x.DuracionMin
	}
	return 0
}

type Temporada struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numero        int32                  `protobuf:"varint,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Episodios     []*Episodio            `protobuf:"bytes,2,rep,name=episodios,proto3" json:"episodios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temporada) Reset() {
	*x = Temporada{}
	mi := &file_proto_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temporada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temporada) ProtoMessage() {}

func (x *Temporada) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temporada.ProtoReflect.Descriptor instead.
func (*Temporada) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *Temporada) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *Temporada) GetEpisodios() []*Episodio {
	if x != nil {
		return x.Episodios
	}
	return nil
}

type FichaTecnicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Sinopsis      string                 `protobuf:"bytes,4,opt,name=sinopsis,proto3" json:"sinopsis,omitempty"`
	Anio          int32                  `protobuf:"varint,5,opt,name=anio,proto3" json:"anio,omitempty"`
	Clasificacion string                 `protobuf:"bytes,6,opt,name=clasificacion,proto3" json:"clasificacion,omitempty"`
	DuracionMin   int32                  `protobuf:"varint,7,opt,name=duracion_min,json=duracionMin,proto3" json:"duracion_min,omitempty"`
	Generos       string                 `protobuf:"bytes,8,opt,name=generos,proto3" json:"generos,omitempty"`
	Categorias    string                 `protobuf:"bytes,9,opt,name=categorias,proto3" json:"categorias,omitempty"`
	Reparto       []*MiembroReparto      `protobuf:"bytes,10,rep,name=reparto,proto3" json:"reparto,omitempty"`
	Temporadas    []*Temporada           `protobuf:"bytes,11,rep,name=temporadas,proto3" json:"temporadas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FichaTecnicaResponse) Reset() {
	*x = FichaTecnicaResponse{}
	mi := &file_proto_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FichaTecnicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FichaTecnicaResponse) ProtoMessage() {}

func (x *FichaTecnicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FichaTecnicaResponse.ProtoReflect.Descriptor instead.
func (*FichaTecnicaResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *FichaTecnicaResponse) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *FichaTecnicaResponse) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *FichaTecnicaResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *FichaTecnicaResponse) GetSinopsis() string {
	if x != nil {
		return x.Sinopsis
	}
	return ""
}

func (x *FichaTecnicaResponse) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *FichaTecnicaResponse) GetClasificacion() string {
	if x != nil {
		return x.Clasificacion
	}
	return ""
}

func (x *FichaTecnicaResponse) GetDuracionMin() int32 {
	if x != nil {
		return x.DuracionMin
	}
	return 0
}

func (x *FichaTecnicaResponse) GetGeneros() string {
	if x != nil {
		return x.Generos
	}
	return ""
}

func (x *FichaTecnicaResponse) GetCategorias() string {
	if x != nil {
		return x.Categorias
	}
	return ""
}

func (x *FichaTecnicaResponse) GetReparto() []*MiembroReparto {
	if x != nil {
		return x.Reparto
	}
	return nil
}

func (x *FichaTecnicaResponse) GetTemporadas() []*Temporada {
	if x != nil {
		return x.Temporadas
	}
	return nil
}

var File_proto_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x13proto/catalog.proto\x12\n" +
	"catalog.v1\"\x1a\n" +
	"\x18ExplorarCarteleraRequest\"\x90\x01\n" +
	"\x16BuscarContenidoRequest\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\x12\x1c\n" +
	"\tcategoria\x18\x02 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06genero\x18\x03 \x01(\tR\x06genero\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x12\n" +
	"\x04tipo\x18\x05 \x01(\tR\x04tipo\"\xd2\x01\n" +
	"\rItemCartelera\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x12\n" +
	"\x04anio\x18\x04 \x01(\x05R\x04anio\x12$\n" +
	"\rclasificacion\x18\x05 \x01(\tR\rclasificacion\x12\x18\n" +
	"\ageneros\x18\x06 \x01(\tR\ageneros\x12\x1e\n" +
	"\n" +
	"categorias\x18\a \x01(\tR\n" +
	"categorias\"D\n" +
	"\x11CarteleraResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.catalog.v1.ItemCarteleraR\x05items\"8\n" +
	"\x13FichaTecnicaRequest\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\"V\n" +
	"\x0eMiembroReparto\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12\x1c\n" +
	"\tpersonaje\x18\x02 \x01(\tR\tpersonaje\x12\x10\n" +
	"\x03rol\x18\x03 \x01(\tR\x03rol\"]\n" +
	"\bEpisodio\x12\x16\n" +
	"\x06numero\x18\x01 \x01(\x05R\x06numero\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12!\n" +
	"\fduracion_min\x18\x03 \x01(\x05R\vduracionMin\"W\n" +
	"\tTemporada\x12\x16\n" +
	"\x06numero\x18\x01 \x01(\x05R\x06numero\x122\n" +
	"\tepisodios\x18\x02 \x03(\v2\x14.catalog.v1.EpisodioR\tepisodios\"\x85\x03\n" +
	"\x14FichaTecnicaResponse\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x1a\n" +
	"\bsinopsis\x18\x04 \x01(\tR\bsinopsis\x12\x12\n" +
	"\x04anio\x18\x05 \x01(\x05R\x04anio\x12$\n" +
	"\rclasificacion\x18\x06 \x01(\tR\rclasificacion\x12!\n" +
	"\fduracion_min\x18\a \x01(\x05R\vduracionMin\x12\x18\n" +
	"\ageneros\x18\b \x01(\tR\ageneros\x12\x1e\n" +
	"\n" +
	"categorias\x18\t \x01(\tR\n" +
	"categorias\x124\n" +
	"\areparto\x18\n" +
	" \x03(\v2\x1a.catalog.v1.MiembroRepartoR\areparto\x125\n" +
	"\n" +
	"temporadas\x18\v \x03(\v2\x15.catalog.v1.TemporadaR\n" +
	"temporadas2\x9a\x02\n" +
	"\x0eCatalogService\x12X\n" +
	"\x11ExplorarCartelera\x12$.catalog.v1.ExplorarCarteleraRequest\x1a\x1d.catalog.v1.CarteleraResponse\x12T\n" +
	"\x0fBuscarContenido\x12\".catalog.v1.BuscarContenidoRequest\x1a\x1d.catalog.v1.CarteleraResponse\x12X\n" +
	"\x13ObtenerFichaTecnica\x12\x1f.catalog.v1.FichaTecnicaRequest\x1a .catalog.v1.FichaTecnicaResponseB4Z2github.com/grupo4/quetxaltv-gateway/internal/pb;pbb\x06proto3"

var (
	file_proto_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_proto_rawDescData []byte
)

func file_proto_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_proto_rawDesc), len(file_proto_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_proto_rawDescData
}

var file_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_catalog_proto_goTypes = []any{
	(*ExplorarCarteleraRequest)(nil), // 0: catalog.v1.ExplorarCarteleraRequest
	(*BuscarContenidoRequest)(nil),   // 1: catalog.v1.BuscarContenidoRequest
	(*ItemCartelera)(nil),            // 2: catalog.v1.ItemCartelera
	(*CarteleraResponse)(nil),        // 3: catalog.v1.CarteleraResponse
	(*FichaTecnicaRequest)(nil),      // 4: catalog.v1.FichaTecnicaRequest
	(*MiembroReparto)(nil),           // 5: catalog.v1.MiembroReparto
	(*Episodio)(nil),                 // 6: catalog.v1.Episodio
	(*Temporada)(nil),                // 7: catalog.v1.Temporada
	(*FichaTecnicaResponse)(nil),     // 8: catalog.v1.FichaTecnicaResponse
}
var file_proto_catalog_proto_depIdxs = []int32{
	2, // 0: catalog.v1.CarteleraResponse.items:type_name -> catalog.v1.ItemCartelera
	6, // 1: catalog.v1.Temporada.episodios:type_name -> catalog.v1.Episodio
	5, // 2: catalog.v1.FichaTecnicaResponse.reparto:type_name -> catalog.v1.MiembroReparto
	7, // 3: catalog.v1.FichaTecnicaResponse.temporadas:type_name -> catalog.v1.Temporada
	0, // 4: catalog.v1.CatalogService.ExplorarCartelera:input_type -> catalog.v1.ExplorarCarteleraRequest
	1, // 5: catalog.v1.CatalogService.BuscarContenido:input_type -> catalog.v1.BuscarContenidoRequest
	4, // 6: catalog.v1.CatalogService.ObtenerFichaTecnica:input_type -> catalog.v1.FichaTecnicaRequest
	3, // 7: catalog.v1.CatalogService.ExplorarCartelera:output_type -> catalog.v1.CarteleraResponse
	3, // 8: catalog.v1.CatalogService.BuscarContenido:output_type -> catalog.v1.CarteleraResponse
	8, // 9: catalog.v1.CatalogService.ObtenerFichaTecnica:output_type -> catalog.v1.FichaTecnicaResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_catalog_proto_init() }
func file_proto_catalog_proto_init() {
	if File_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_proto_rawDesc), len(file_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_proto = out.File
	file_proto_catalog_proto_goTypes = nil
	file_proto_catalog_proto_depIdxs = nil
}
