// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: proto/catalog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExplorarCarteleraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExplorarCarteleraRequest) Reset() {
	*x = ExplorarCarteleraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExplorarCarteleraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplorarCarteleraRequest) ProtoMessage() {}

func (x *ExplorarCarteleraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplorarCarteleraRequest.ProtoReflect.Descriptor instead.
func (*ExplorarCarteleraRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{0}
}

type BuscarContenidoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Titulo    string `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Categoria string `protobuf:"bytes,2,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Genero    string `protobuf:"bytes,3,opt,name=genero,proto3" json:"genero,omitempty"`
	Actor     string `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *BuscarContenidoRequest) Reset() {
	*x = BuscarContenidoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarContenidoRequest) ProtoMessage() {}

func (x *BuscarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarContenidoRequest.ProtoReflect.Descriptor instead.
func (*BuscarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *BuscarContenidoRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *BuscarContenidoRequest) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *BuscarContenidoRequest) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *BuscarContenidoRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type ItemCartelera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContenidoId   string `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Titulo        string `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo          string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Anio          int32  `protobuf:"varint,4,opt,name=anio,proto3" json:"anio,omitempty"`
	Clasificacion string `protobuf:"bytes,5,opt,name=clasificacion,proto3" json:"clasificacion,omitempty"`
	Generos       string `protobuf:"bytes,6,opt,name=generos,proto3" json:"generos,omitempty"`
	Categorias    string `protobuf:"bytes,7,opt,name=categorias,proto3" json:"categorias,omitempty"`
}

func (x *ItemCartelera) Reset() {
	*x = ItemCartelera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemCartelera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCartelera) ProtoMessage() {}

func (x *ItemCartelera) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCartelera.ProtoReflect.Descriptor instead.
func (*ItemCartelera) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ItemCartelera) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *ItemCartelera) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *ItemCartelera) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ItemCartelera) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *ItemCartelera) GetClasificacion() string {
	if x != nil {
		return x.Clasificacion
	}
	return ""
}

func (x *ItemCartelera) GetGeneros() string {
	if x != nil {
		return x.Generos
	}
	return ""
}

func (x *ItemCartelera) GetCategorias() string {
	if x != nil {
		return x.Categorias
	}
	return ""
}

type CarteleraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ItemCartelera `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CarteleraResponse) Reset() {
	*x = CarteleraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarteleraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarteleraResponse) ProtoMessage() {}

func (x *CarteleraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarteleraResponse.ProtoReflect.Descriptor instead.
func (*CarteleraResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CarteleraResponse) GetItems() []*ItemCartelera {
	if x != nil {
		return x.Items
	}
	return nil
}

type FichaTecnicaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContenidoId string `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
}

func (x *FichaTecnicaRequest) Reset() {
	*x = FichaTecnicaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FichaTecnicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FichaTecnicaRequest) ProtoMessage() {}

func (x *FichaTecnicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FichaTecnicaRequest.ProtoReflect.Descriptor instead.
func (*FichaTecnicaRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *FichaTecnicaRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type MiembroReparto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor     string `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Personaje string `protobuf:"bytes,2,opt,name=personaje,proto3" json:"personaje,omitempty"`
	Rol       string `protobuf:"bytes,3,opt,name=rol,proto3" json:"rol,omitempty"`
}

func (x *MiembroReparto) Reset() {
	*x = MiembroReparto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiembroReparto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiembroReparto) ProtoMessage() {}

func (x *MiembroReparto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiembroReparto.ProtoReflect.Descriptor instead.
func (*MiembroReparto) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *MiembroReparto) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *MiembroReparto) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

func (x *MiembroReparto) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

type Episodio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numero      int32  `protobuf:"varint,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Titulo      string `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	DuracionMin int32  `protobuf:"varint,3,opt,name=duracion_min,json=duracionMin,proto3" json:"duracion_min,omitempty"`
}

func (x *Episodio) Reset() {
	*x = Episodio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Episodio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episodio) ProtoMessage() {}

func (x *Episodio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episodio.ProtoReflect.Descriptor instead.
func (*Episodio) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *Episodio) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *Episodio) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Episodio) GetDuracionMin() int32 {
	if x != nil {
		return x.DuracionMin
	}
	return 0
}

type Temporada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numero    int32       `protobuf:"varint,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Episodios []*Episodio `protobuf:"bytes,2,rep,name=episodios,proto3" json:"episodios,omitempty"`
}

func (x *Temporada) Reset() {
	*x = Temporada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temporada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temporada) ProtoMessage() {}

func (x *Temporada) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temporada.ProtoReflect.Descriptor instead.
func (*Temporada) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *Temporada) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *Temporada) GetEpisodios() []*Episodio {
	if x != nil {
		return x.Episodios
	}
	return nil
}

type FichaTecnicaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContenidoId   string            `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Titulo        string            `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo          string            `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Sinopsis      string            `protobuf:"bytes,4,opt,name=sinopsis,proto3" json:"sinopsis,omitempty"`
	Anio          int32             `protobuf:"varint,5,opt,name=anio,proto3" json:"anio,omitempty"`
	Clasificacion string            `protobuf:"bytes,6,opt,name=clasificacion,proto3" json:"clasificacion,omitempty"`
	DuracionMin   int32             `protobuf:"varint,7,opt,name=duracion_min,json=duracionMin,proto3" json:"duracion_min,omitempty"`
	Generos       string            `protobuf:"bytes,8,opt,name=generos,proto3" json:"generos,omitempty"`
	Categorias    string            `protobuf:"bytes,9,opt,name=categorias,proto3" json:"categorias,omitempty"`
	Reparto       []*MiembroReparto `protobuf:"bytes,10,rep,name=reparto,proto3" json:"reparto,omitempty"`
	Temporadas    []*Temporada      `protobuf:"bytes,11,rep,name=temporadas,proto3" json:"temporadas,omitempty"`
}

func (x *FichaTecnicaResponse) Reset() {
	*x = FichaTecnicaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_catalog_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FichaTecnicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FichaTecnicaResponse) ProtoMessage() {}

func (x *FichaTecnicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FichaTecnicaResponse.ProtoReflect.Descriptor instead.
func (*FichaTecnicaResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *FichaTecnicaResponse) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *FichaTecnicaResponse) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *FichaTecnicaResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *FichaTecnicaResponse) GetSinopsis() string {
	if x != nil {
		return x.Sinopsis
	}
	return ""
}

func (x *FichaTecnicaResponse) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *FichaTecnicaResponse) GetClasificacion() string {
	if x != nil {
		return x.Clasificacion
	}
	return ""
}

func (x *FichaTecnicaResponse) GetDuracionMin() int32 {
	if x != nil {
		return x.DuracionMin
	}
	return 0
}

func (x *FichaTecnicaResponse) GetGeneros() string {
	if x != nil {
		return x.Generos
	}
	return ""
}

func (x *FichaTecnicaResponse) GetCategorias() string {
	if x != nil {
		return x.Categorias
	}
	return ""
}

func (x *FichaTecnicaResponse) GetReparto() []*MiembroReparto {
	if x != nil {
		return x.Reparto
	}
	return nil
}

func (x *FichaTecnicaResponse) GetTemporadas() []*Temporada {
	if x != nil {
		return x.Temporadas
	}
	return nil
}

var File_proto_catalog_proto protoreflect.FileDescriptor

var file_proto_catalog_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76,
	0x31, 0x22, 0x1a, 0x0a, 0x18, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x61, 0x72, 0x43, 0x61, 0x72,
	0x74, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7c, 0x0a,
	0x16, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xd2, 0x01, 0x0a, 0x0d,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x6e, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x6e, 0x69, 0x6f,
	0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x61, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x61, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73,
	0x22, 0x44, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x38, 0x0a, 0x13, 0x46, 0x69, 0x63, 0x68, 0x61, 0x54,
	0x65, 0x63, 0x6e, 0x69, 0x63, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x49, 0x64,
	0x22, 0x56, 0x0a, 0x0e, 0x4d, 0x69, 0x65, 0x6d, 0x62, 0x72, 0x6f, 0x52, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x6a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x6f, 0x6c, 0x22, 0x5d, 0x0a, 0x08, 0x45, 0x70, 0x69, 0x73,
	0x6f, 0x64, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69,
	0x74, 0x75, 0x6c, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x75, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x75, 0x72, 0x61,
	0x63, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x22, 0x57, 0x0a, 0x09, 0x54, 0x65, 0x6d, 0x70, 0x6f,
	0x72, 0x61, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x12, 0x32, 0x0a, 0x09,
	0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x69, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x70, 0x69,
	0x73, 0x6f, 0x64, 0x69, 0x6f, 0x52, 0x09, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x69, 0x6f, 0x73,
	0x22, 0x85, 0x03, 0x0a, 0x14, 0x46, 0x69, 0x63, 0x68, 0x61, 0x54, 0x65, 0x63, 0x6e, 0x69, 0x63,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69,
	0x74, 0x75, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x6e, 0x6f,
	0x70, 0x73, 0x69, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x69, 0x6e, 0x6f,
	0x70, 0x73, 0x69, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x6e, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x61, 0x6e, 0x69, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x61, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6c, 0x61, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x75, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x4d, 0x69,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6f, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x65, 0x6d, 0x62, 0x72,
	0x6f, 0x52, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6f, 0x52, 0x07, 0x72, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6f, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x64, 0x61, 0x73, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x64, 0x61, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x64, 0x61, 0x73, 0x32, 0x9a, 0x02, 0x0a, 0x0e, 0x43, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x72, 0x61, 0x72, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x72, 0x61,
	0x12, 0x24, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78,
	0x70, 0x6c, 0x6f, 0x72, 0x61, 0x72, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x65, 0x6c,
	0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x13, 0x4f,
	0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x46, 0x69, 0x63, 0x68, 0x61, 0x54, 0x65, 0x63, 0x6e, 0x69,
	0x63, 0x61, 0x12, 0x1f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x63, 0x68, 0x61, 0x54, 0x65, 0x63, 0x6e, 0x69, 0x63, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x63, 0x68, 0x61, 0x54, 0x65, 0x63, 0x6e, 0x69, 0x63, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x34, 0x2f, 0x71, 0x75, 0x65, 0x74, 0x78,
	0x61, 0x6c, 0x74, 0x76, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_proto_rawDescData = file_proto_catalog_proto_rawDesc
)

func file_proto_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_catalog_proto_rawDescData)
	})
	return file_proto_catalog_proto_rawDescData
}

var file_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_catalog_proto_goTypes = []interface{}{
	(*ExplorarCarteleraRequest)(nil), // 0: catalog.v1.ExplorarCarteleraRequest
	(*BuscarContenidoRequest)(nil),   // 1: catalog.v1.BuscarContenidoRequest
	(*ItemCartelera)(nil),            // 2: catalog.v1.ItemCartelera
	(*CarteleraResponse)(nil),        // 3: catalog.v1.CarteleraResponse
	(*FichaTecnicaRequest)(nil),      // 4: catalog.v1.FichaTecnicaRequest
	(*MiembroReparto)(nil),           // 5: catalog.v1.MiembroReparto
	(*Episodio)(nil),                 // 6: catalog.v1.Episodio
	(*Temporada)(nil),                // 7: catalog.v1.Temporada
	(*FichaTecnicaResponse)(nil),     // 8: catalog.v1.FichaTecnicaResponse
}
var file_proto_catalog_proto_depIdxs = []int32{
	2, // 0: catalog.v1.CarteleraResponse.items:type_name -> catalog.v1.ItemCartelera
	6, // 1: catalog.v1.Temporada.episodios:type_name -> catalog.v1.Episodio
	5, // 2: catalog.v1.FichaTecnicaResponse.reparto:type_name -> catalog.v1.MiembroReparto
	7, // 3: catalog.v1.FichaTecnicaResponse.temporadas:type_name -> catalog.v1.Temporada
	0, // 4: catalog.v1.CatalogService.ExplorarCartelera:input_type -> catalog.v1.ExplorarCarteleraRequest
	1, // 5: catalog.v1.CatalogService.BuscarContenido:input_type -> catalog.v1.BuscarContenidoRequest
	4, // 6: catalog.v1.CatalogService.ObtenerFichaTecnica:input_type -> catalog.v1.FichaTecnicaRequest
	3, // 7: catalog.v1.CatalogService.ExplorarCartelera:output_type -> catalog.v1.CarteleraResponse
	3, // 8: catalog.v1.CatalogService.BuscarContenido:output_type -> catalog.v1.CarteleraResponse
	8, // 9: catalog.v1.CatalogService.ObtenerFichaTecnica:output_type -> catalog.v1.FichaTecnicaResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_catalog_proto_init() }
func file_proto_catalog_proto_init() {
	if File_proto_catalog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_catalog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExplorarCarteleraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscarContenidoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemCartelera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarteleraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FichaTecnicaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiembroReparto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Episodio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Temporada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_catalog_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FichaTecnicaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_catalog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_proto = out.File
	file_proto_catalog_proto_rawDesc = nil
	file_proto_catalog_proto_goTypes = nil
	file_proto_catalog_proto_depIdxs = nil
}
