// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/fx.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertirMontoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monto         float64                `protobuf:"fixed64,1,opt,name=monto,proto3" json:"monto,omitempty"`
	MonedaOrigen  string                 `protobuf:"bytes,2,opt,name=moneda_origen,json=monedaOrigen,proto3" json:"moneda_origen,omitempty"`
	MonedaDestino string                 `protobuf:"bytes,3,opt,name=moneda_destino,json=monedaDestino,proto3" json:"moneda_destino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertirMontoRequest) Reset() {
	*x = ConvertirMontoRequest{}
	mi := &file_proto_fx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertirMontoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertirMontoRequest) ProtoMessage() {}

func (x *ConvertirMontoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertirMontoRequest.ProtoReflect.Descriptor instead.
func (*ConvertirMontoRequest) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertirMontoRequest) GetMonto() float64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

func (x *ConvertirMontoRequest) GetMonedaOrigen() string {
	if x != nil {
		return x.MonedaOrigen
	}
	return ""
}

func (x *ConvertirMontoRequest) GetMonedaDestino() string {
	if x != nil {
		return x.MonedaDestino
	}
	return ""
}

type ConvertirMontoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MontoOriginal   float64                `protobuf:"fixed64,1,opt,name=monto_original,json=montoOriginal,proto3" json:"monto_original,omitempty"`
	MontoConvertido float64                `protobuf:"fixed64,2,opt,name=monto_convertido,json=montoConvertido,proto3" json:"monto_convertido,omitempty"`
	MonedaOrigen    string                 `protobuf:"bytes,3,opt,name=moneda_origen,json=monedaOrigen,proto3" json:"moneda_origen,omitempty"`
	MonedaDestino   string                 `protobuf:"bytes,4,opt,name=moneda_destino,json=monedaDestino,proto3" json:"moneda_destino,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertirMontoResponse) Reset() {
	*x = ConvertirMontoResponse{}
	mi := &file_proto_fx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertirMontoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertirMontoResponse) ProtoMessage() {}

func (x *ConvertirMontoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertirMontoResponse.ProtoReflect.Descriptor instead.
func (*ConvertirMontoResponse) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertirMontoResponse) GetMontoOriginal() float64 {
	if x != nil {
		return x.MontoOriginal
	}
	return 0
}

func (x *ConvertirMontoResponse) GetMontoConvertido() float64 {
	if x != nil {
		return x.MontoConvertido
	}
	return 0
}

func (x *ConvertirMontoResponse) GetMonedaOrigen() string {
	if x != nil {
		return x.MonedaOrigen
	}
	return ""
}

func (x *ConvertirMontoResponse) GetMonedaDestino() string {
	if x != nil {
		return x.MonedaDestino
	}
	return ""
}

type ConsultarTasaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonedaOrigen  string                 `protobuf:"bytes,1,opt,name=moneda_origen,json=monedaOrigen,proto3" json:"moneda_origen,omitempty"`
	MonedaDestino string                 `protobuf:"bytes,2,opt,name=moneda_destino,json=monedaDestino,proto3" json:"moneda_destino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarTasaRequest) Reset() {
	*x = ConsultarTasaRequest{}
	mi := &file_proto_fx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarTasaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarTasaRequest) ProtoMessage() {}

func (x *ConsultarTasaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarTasaRequest.ProtoReflect.Descriptor instead.
func (*ConsultarTasaRequest) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{2}
}

func (x *ConsultarTasaRequest) GetMonedaOrigen() string {
	if x != nil {
		return x.MonedaOrigen
	}
	return ""
}

func (x *ConsultarTasaRequest) GetMonedaDestino() string {
	if x != nil {
		return x.MonedaDestino
	}
	return ""
}

type ConsultarTasaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasa          float64                `protobuf:"fixed64,1,opt,name=tasa,proto3" json:"tasa,omitempty"`
	MonedaOrigen  string                 `protobuf:"bytes,2,opt,name=moneda_origen,json=monedaOrigen,proto3" json:"moneda_origen,omitempty"`
	MonedaDestino string                 `protobuf:"bytes,3,opt,name=moneda_destino,json=monedaDestino,proto3" json:"moneda_destino,omitempty"`
	DesdeCache    bool                   `protobuf:"varint,4,opt,name=desde_cache,json=desdeCache,proto3" json:"desde_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarTasaResponse) Reset() {
	*x = ConsultarTasaResponse{}
	mi := &file_proto_fx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarTasaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarTasaResponse) ProtoMessage() {}

func (x *ConsultarTasaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarTasaResponse.ProtoReflect.Descriptor instead.
func (*ConsultarTasaResponse) Descriptor() ([]byte, []int) {
	return file_proto_fx_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultarTasaResponse) GetTasa() float64 {
	if x != nil {
		return x.Tasa
	}
	return 0
}

func (x *ConsultarTasaResponse) GetMonedaOrigen() string {
	if x != nil {
		return x.MonedaOrigen
	}
	return ""
}

func (x *ConsultarTasaResponse) GetMonedaDestino() string {
	if x != nil {
		return x.MonedaDestino
	}
	return ""
}

func (x *ConsultarTasaResponse) GetDesdeCache() bool {
	if x != nil {
		return x.DesdeCache
	}
	return false
}

var File_proto_fx_proto protoreflect.FileDescriptor

const file_proto_fx_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/fx.proto\x12\x05fx.v1\"y\n" +
	"\x15ConvertirMontoRequest\x12\x14\n" +
	"\x05monto\x18\x01 \x01(\x01R\x05monto\x12#\n" +
	"\rmoneda_origen\x18\x02 \x01(\tR\fmonedaOrigen\x12%\n" +
	"\x0emoneda_destino\x18\x03 \x01(\tR\rmonedaDestino\"\xb6\x01\n" +
	"\x16ConvertirMontoResponse\x12%\n" +
	"\x0emonto_original\x18\x01 \x01(\x01R\rmontoOriginal\x12)\n" +
	"\x10monto_convertido\x18\x02 \x01(\x01R\x0fmontoConvertido\x12#\n" +
	"\rmoneda_origen\x18\x03 \x01(\tR\fmonedaOrigen\x12%\n" +
	"\x0emoneda_destino\x18\x04 \x01(\tR\rmonedaDestino\"b\n" +
	"\x14ConsultarTasaRequest\x12#\n" +
	"\rmoneda_origen\x18\x01 \x01(\tR\fmonedaOrigen\x12%\n" +
	"\x0emoneda_destino\x18\x02 \x01(\tR\rmonedaDestino\"\x98\x01\n" +
	"\x15ConsultarTasaResponse\x12\x12\n" +
	"\x04tasa\x18\x01 \x01(\x01R\x04tasa\x12#\n" +
	"\rmoneda_origen\x18\x02 \x01(\tR\fmonedaOrigen\x12%\n" +
	"\x0emoneda_destino\x18\x03 \x01(\tR\rmonedaDestino\x12\x1f\n" +
	"\vdesde_cache\x18\x04 \x01(\bR\n" +
	"desdeCache2\xa6\x01\n" +
	"\tFXService\x12M\n" +
	"\x0eConvertirMonto\x12\x1c.fx.v1.ConvertirMontoRequest\x1a\x1d.fx.v1.ConvertirMontoResponse\x12J\n" +
	"\rConsultarTasa\x12\x1b.fx.v1.ConsultarTasaRequest\x1a\x1c.fx.v1.ConsultarTasaResponseB4Z2github.com/grupo4/quetxaltv-gateway/internal/pb;pbb\x06proto3"

var (
	file_proto_fx_proto_rawDescOnce sync.Once
	file_proto_fx_proto_rawDescData []byte
)

func file_proto_fx_proto_rawDescGZIP() []byte {
	file_proto_fx_proto_rawDescOnce.Do(func() {
		file_proto_fx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fx_proto_rawDesc), len(file_proto_fx_proto_rawDesc)))
	})
	return file_proto_fx_proto_rawDescData
}

var file_proto_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_fx_proto_goTypes = []any{
	(*ConvertirMontoRequest)(nil),  // 0: fx.v1.ConvertirMontoRequest
	(*ConvertirMontoResponse)(nil), // 1: fx.v1.ConvertirMontoResponse
	(*ConsultarTasaRequest)(nil),   // 2: fx.v1.ConsultarTasaRequest
	(*ConsultarTasaResponse)(nil),  // 3: fx.v1.ConsultarTasaResponse
}
var file_proto_fx_proto_depIdxs = []int32{
	0, // 0: fx.v1.FXService.ConvertirMonto:input_type -> fx.v1.ConvertirMontoRequest
	2, // 1: fx.v1.FXService.ConsultarTasa:input_type -> fx.v1.ConsultarTasaRequest
	1, // 2: fx.v1.FXService.ConvertirMonto:output_type -> fx.v1.ConvertirMontoResponse
	3, // 3: fx.v1.FXService.ConsultarTasa:output_type -> fx.v1.ConsultarTasaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fx_proto_init() }
func file_proto_fx_proto_init() {
	if File_proto_fx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fx_proto_rawDesc), len(file_proto_fx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fx_proto_goTypes,
		DependencyIndexes: file_proto_fx_proto_depIdxs,
		MessageInfos:      file_proto_fx_proto_msgTypes,
	}.Build()
	File_proto_fx_proto = out.File
	file_proto_fx_proto_goTypes = nil
	file_proto_fx_proto_depIdxs = nil
}
