// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/fx.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FXService_ConvertirMonto_FullMethodName = "/fx.v1.FXService/ConvertirMonto"
	FXService_ConsultarTasa_FullMethodName  = "/fx.v1.FXService/ConsultarTasa"
)

// FXServiceClient is the client API for FXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FXServiceClient interface {
	ConvertirMonto(ctx context.Context, in *ConvertirMontoRequest, opts ...grpc.CallOption) (*ConvertirMontoResponse, error)
	ConsultarTasa(ctx context.Context, in *ConsultarTasaRequest, opts ...grpc.CallOption) (*ConsultarTasaResponse, error)
}

type fXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFXServiceClient(cc grpc.ClientConnInterface) FXServiceClient {
	return &fXServiceClient{cc}
}

func (c *fXServiceClient) ConvertirMonto(ctx context.Context, in *ConvertirMontoRequest, opts ...grpc.CallOption) (*ConvertirMontoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertirMontoResponse)
	err := c.cc.Invoke(ctx, FXService_ConvertirMonto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) ConsultarTasa(ctx context.Context, in *ConsultarTasaRequest, opts ...grpc.CallOption) (*ConsultarTasaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarTasaResponse)
	err := c.cc.Invoke(ctx, FXService_ConsultarTasa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FXServiceServer is the server API for FXService service.
// All implementations must embed UnimplementedFXServiceServer
// for forward compatibility.
type FXServiceServer interface {
	ConvertirMonto(context.Context, *ConvertirMontoRequest) (*ConvertirMontoResponse, error)
	ConsultarTasa(context.Context, *ConsultarTasaRequest) (*ConsultarTasaResponse, error)
	mustEmbedUnimplementedFXServiceServer()
}

// UnimplementedFXServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFXServiceServer struct{}

func (UnimplementedFXServiceServer) ConvertirMonto(context.Context, *ConvertirMontoRequest) (*ConvertirMontoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertirMonto not implemented")
}
func (UnimplementedFXServiceServer) ConsultarTasa(context.Context, *ConsultarTasaRequest) (*ConsultarTasaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarTasa not implemented")
}
func (UnimplementedFXServiceServer) mustEmbedUnimplementedFXServiceServer() {}
func (UnimplementedFXServiceServer) testEmbeddedByValue()                   {}

// UnsafeFXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FXServiceServer will
// result in compilation errors.
type UnsafeFXServiceServer interface {
	mustEmbedUnimplementedFXServiceServer()
}

func RegisterFXServiceServer(s grpc.ServiceRegistrar, srv FXServiceServer) {
	// If the following call panics, it indicates UnimplementedFXServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FXService_ServiceDesc, srv)
}

func _FXService_ConvertirMonto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertirMontoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).ConvertirMonto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_ConvertirMonto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).ConvertirMonto(ctx, req.(*ConvertirMontoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_ConsultarTasa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarTasaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).ConsultarTasa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_ConsultarTasa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).ConsultarTasa(ctx, req.(*ConsultarTasaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FXService_ServiceDesc is the grpc.ServiceDesc for FXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fx.v1.FXService",
	HandlerType: (*FXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertirMonto",
			Handler:    _FXService_ConvertirMonto_Handler,
		},
		{
			MethodName: "ConsultarTasa",
			Handler:    _FXService_ConsultarTasa_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fx.proto",
}
