// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/notifications.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncolarCorreoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Destinatario  string                 `protobuf:"bytes,3,opt,name=destinatario,proto3" json:"destinatario,omitempty"`
	Datos         map[string]string      `protobuf:"bytes,4,rep,name=datos,proto3" json:"datos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncolarCorreoRequest) Reset() {
	*x = EncolarCorreoRequest{}
	mi := &file_proto_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncolarCorreoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncolarCorreoRequest) ProtoMessage() {}

func (x *EncolarCorreoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncolarCorreoRequest.ProtoReflect.Descriptor instead.
func (*EncolarCorreoRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *EncolarCorreoRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *EncolarCorreoRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *EncolarCorreoRequest) GetDestinatario() string {
	if x != nil {
		return x.Destinatario
	}
	return ""
}

func (x *EncolarCorreoRequest) GetDatos() map[string]string {
	if x != nil {
		return x.Datos
	}
	return nil
}

type EncolarCorreoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncolarCorreoResponse) Reset() {
	*x = EncolarCorreoResponse{}
	mi := &file_proto_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncolarCorreoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncolarCorreoResponse) ProtoMessage() {}

func (x *EncolarCorreoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncolarCorreoResponse.ProtoReflect.Descriptor instead.
func (*EncolarCorreoResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *EncolarCorreoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncolarCorreoResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_proto_notifications_proto protoreflect.FileDescriptor

const file_proto_notifications_proto_rawDesc = "" +
	"\n" +
	"\x19proto/notifications.proto\x12\x0fnotification.v1\"\xef\x01\n" +
	"\x14EncolarCorreoRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\"\n" +
	"\fdestinatario\x18\x03 \x01(\tR\fdestinatario\x12F\n" +
	"\x05datos\x18\x04 \x03(\v20.notification.v1.EncolarCorreoRequest.DatosEntryR\x05datos\x1a8\n" +
	"\n" +
	"DatosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x15EncolarCorreoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado2u\n" +
	"\x13NotificationService\x12^\n" +
	"\rEncolarCorreo\x12%.notification.v1.EncolarCorreoRequest\x1a&.notification.v1.EncolarCorreoResponseB1Z/github.com/grupo4/quetxaltv-gateway/internal/pbb\x06proto3"

var (
	file_proto_notifications_proto_rawDescOnce sync.Once
	file_proto_notifications_proto_rawDescData []byte
)

func file_proto_notifications_proto_rawDescGZIP() []byte {
	file_proto_notifications_proto_rawDescOnce.Do(func() {
		file_proto_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notifications_proto_rawDesc), len(file_proto_notifications_proto_rawDesc)))
	})
	return file_proto_notifications_proto_rawDescData
}

var file_proto_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_notifications_proto_goTypes = []any{
	(*EncolarCorreoRequest)(nil),  // 0: notification.v1.EncolarCorreoRequest
	(*EncolarCorreoResponse)(nil), // 1: notification.v1.EncolarCorreoResponse
	nil,                           // 2: notification.v1.EncolarCorreoRequest.DatosEntry
}
var file_proto_notifications_proto_depIdxs = []int32{
	2, // 0: notification.v1.EncolarCorreoRequest.datos:type_name -> notification.v1.EncolarCorreoRequest.DatosEntry
	0, // 1: notification.v1.NotificationService.EncolarCorreo:input_type -> notification.v1.EncolarCorreoRequest
	1, // 2: notification.v1.NotificationService.EncolarCorreo:output_type -> notification.v1.EncolarCorreoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_notifications_proto_init() }
func file_proto_notifications_proto_init() {
	if File_proto_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notifications_proto_rawDesc), len(file_proto_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notifications_proto_goTypes,
		DependencyIndexes: file_proto_notifications_proto_depIdxs,
		MessageInfos:      file_proto_notifications_proto_msgTypes,
	}.Build()
	File_proto_notifications_proto = out.File
	file_proto_notifications_proto_goTypes = nil
	file_proto_notifications_proto_depIdxs = nil
}
