// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/rating.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalificarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerfilId      string                 `protobuf:"bytes,1,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor         int32                  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalificarRequest) Reset() {
	*x = CalificarRequest{}
	mi := &file_proto_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalificarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalificarRequest) ProtoMessage() {}

func (x *CalificarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalificarRequest.ProtoReflect.Descriptor instead.
func (*CalificarRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{0}
}

func (x *CalificarRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *CalificarRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *CalificarRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CalificarRequest) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type RecomendacionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId    string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	TotalVotos     int32                  `protobuf:"varint,2,opt,name=total_votos,json=totalVotos,proto3" json:"total_votos,omitempty"`
	VotosPositivos int32                  `protobuf:"varint,3,opt,name=votos_positivos,json=votosPositivos,proto3" json:"votos_positivos,omitempty"`
	Porcentaje     float64                `protobuf:"fixed64,4,opt,name=porcentaje,proto3" json:"porcentaje,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecomendacionResponse) Reset() {
	*x = RecomendacionResponse{}
	mi := &file_proto_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomendacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomendacionResponse) ProtoMessage() {}

func (x *RecomendacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomendacionResponse.ProtoReflect.Descriptor instead.
func (*RecomendacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{1}
}

func (x *RecomendacionResponse) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *RecomendacionResponse) GetTotalVotos() int32 {
	if x != nil {
		return x.TotalVotos
	}
	return 0
}

func (x *RecomendacionResponse) GetVotosPositivos() int32 {
	if x != nil {
		return x.VotosPositivos
	}
	return 0
}

func (x *RecomendacionResponse) GetPorcentaje() float64 {
	if x != nil {
		return x.Porcentaje
	}
	return 0
}

type ObtenerRecomendacionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerRecomendacionRequest) Reset() {
	*x = ObtenerRecomendacionRequest{}
	mi := &file_proto_rating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerRecomendacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerRecomendacionRequest) ProtoMessage() {}

func (x *ObtenerRecomendacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerRecomendacionRequest.ProtoReflect.Descriptor instead.
func (*ObtenerRecomendacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{2}
}

func (x *ObtenerRecomendacionRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type ObtenerCalificacionUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerfilId      string                 `protobuf:"bytes,1,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerCalificacionUsuarioRequest) Reset() {
	*x = ObtenerCalificacionUsuarioRequest{}
	mi := &file_proto_rating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerCalificacionUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerCalificacionUsuarioRequest) ProtoMessage() {}

func (x *ObtenerCalificacionUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerCalificacionUsuarioRequest.ProtoReflect.Descriptor instead.
func (*ObtenerCalificacionUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{3}
}

func (x *ObtenerCalificacionUsuarioRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *ObtenerCalificacionUsuarioRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type CalificacionUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existe        bool                   `protobuf:"varint,1,opt,name=existe,proto3" json:"existe,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor         int32                  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalificacionUsuarioResponse) Reset() {
	*x = CalificacionUsuarioResponse{}
	mi := &file_proto_rating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalificacionUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalificacionUsuarioResponse) ProtoMessage() {}

func (x *CalificacionUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalificacionUsuarioResponse.ProtoReflect.Descriptor instead.
func (*CalificacionUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{4}
}

func (x *CalificacionUsuarioResponse) GetExiste() bool {
	if x != nil {
		return x.Existe
	}
	return false
}

func (x *CalificacionUsuarioResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CalificacionUsuarioResponse) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

var File_proto_rating_proto protoreflect.FileDescriptor

const file_proto_rating_proto_rawDesc = "" +
	"\n" +
	"\x12proto/rating.proto\x12\trating.v1\"|\n" +
	"\x10CalificarRequest\x12\x1b\n" +
	"\tperfil_id\x18\x01 \x01(\tR\bperfilId\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x14\n" +
	"\x05valor\x18\x04 \x01(\x05R\x05valor\"\xa4\x01\n" +
	"\x15RecomendacionResponse\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\x12\x1f\n" +
	"\vtotal_votos\x18\x02 \x01(\x05R\n" +
	"totalVotos\x12'\n" +
	"\x0fvotos_positivos\x18\x03 \x01(\x05R\x0evotosPositivos\x12\x1e\n" +
	"\n" +
	"porcentaje\x18\x04 \x01(\x01R\n" +
	"porcentaje\"@\n" +
	"\x1bObtenerRecomendacionRequest\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\"c\n" +
	"!ObtenerCalificacionUsuarioRequest\x12\x1b\n" +
	"\tperfil_id\x18\x01 \x01(\tR\bperfilId\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId\"_\n" +
	"\x1bCalificacionUsuarioResponse\x12\x16\n" +
	"\x06existe\x18\x01 \x01(\bR\x06existe\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\x14\n" +
	"\x05valor\x18\x03 \x01(\x05R\x05valor2\xb1\x02\n" +
	"\rRatingService\x12J\n" +
	"\tCalificar\x12\x1b.rating.v1.CalificarRequest\x1a .rating.v1.RecomendacionResponse\x12`\n" +
	"\x14ObtenerRecomendacion\x12&.rating.v1.ObtenerRecomendacionRequest\x1a .rating.v1.RecomendacionResponse\x12r\n" +
	"\x1aObtenerCalificacionUsuario\x12,.rating.v1.ObtenerCalificacionUsuarioRequest\x1a&.rating.v1.CalificacionUsuarioResponseB4Z2github.com/grupo4/quetxaltv-gateway/internal/pb;pbb\x06proto3"

var (
	file_proto_rating_proto_rawDescOnce sync.Once
	file_proto_rating_proto_rawDescData []byte
)

func file_proto_rating_proto_rawDescGZIP() []byte {
	file_proto_rating_proto_rawDescOnce.Do(func() {
		file_proto_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rating_proto_rawDesc), len(file_proto_rating_proto_rawDesc)))
	})
	return file_proto_rating_proto_rawDescData
}

var file_proto_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rating_proto_goTypes = []any{
	(*CalificarRequest)(nil),                  // 0: rating.v1.CalificarRequest
	(*RecomendacionResponse)(nil),             // 1: rating.v1.RecomendacionResponse
	(*ObtenerRecomendacionRequest)(nil),       // 2: rating.v1.ObtenerRecomendacionRequest
	(*ObtenerCalificacionUsuarioRequest)(nil), // 3: rating.v1.ObtenerCalificacionUsuarioRequest
	(*CalificacionUsuarioResponse)(nil),       // 4: rating.v1.CalificacionUsuarioResponse
}
var file_proto_rating_proto_depIdxs = []int32{
	0, // 0: rating.v1.RatingService.Calificar:input_type -> rating.v1.CalificarRequest
	2, // 1: rating.v1.RatingService.ObtenerRecomendacion:input_type -> rating.v1.ObtenerRecomendacionRequest
	3, // 2: rating.v1.RatingService.ObtenerCalificacionUsuario:input_type -> rating.v1.ObtenerCalificacionUsuarioRequest
	1, // 3: rating.v1.RatingService.Calificar:output_type -> rating.v1.RecomendacionResponse
	1, // 4: rating.v1.RatingService.ObtenerRecomendacion:output_type -> rating.v1.RecomendacionResponse
	4, // 5: rating.v1.RatingService.ObtenerCalificacionUsuario:output_type -> rating.v1.CalificacionUsuarioResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rating_proto_init() }
func file_proto_rating_proto_init() {
	if File_proto_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rating_proto_rawDesc), len(file_proto_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rating_proto_goTypes,
		DependencyIndexes: file_proto_rating_proto_depIdxs,
		MessageInfos:      file_proto_rating_proto_msgTypes,
	}.Build()
	File_proto_rating_proto = out.File
	file_proto_rating_proto_goTypes = nil
	file_proto_rating_proto_depIdxs = nil
}
