// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/rating.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RatingService_Calificar_FullMethodName                  = "/rating.v1.RatingService/Calificar"
	RatingService_ObtenerRecomendacion_FullMethodName       = "/rating.v1.RatingService/ObtenerRecomendacion"
	RatingService_ObtenerCalificacionUsuario_FullMethodName = "/rating.v1.RatingService/ObtenerCalificacionUsuario"
)

// RatingServiceClient is the client API for RatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatingServiceClient interface {
	Calificar(ctx context.Context, in *CalificarRequest, opts ...grpc.CallOption) (*RecomendacionResponse, error)
	ObtenerRecomendacion(ctx context.Context, in *ObtenerRecomendacionRequest, opts ...grpc.CallOption) (*RecomendacionResponse, error)
	ObtenerCalificacionUsuario(ctx context.Context, in *ObtenerCalificacionUsuarioRequest, opts ...grpc.CallOption) (*CalificacionUsuarioResponse, error)
}

type ratingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingServiceClient(cc grpc.ClientConnInterface) RatingServiceClient {
	return &ratingServiceClient{cc}
}

func (c *ratingServiceClient) Calificar(ctx context.Context, in *CalificarRequest, opts ...grpc.CallOption) (*RecomendacionResponse, error) {
	out := new(RecomendacionResponse)
	err := c.cc.Invoke(ctx, RatingService_Calificar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) ObtenerRecomendacion(ctx context.Context, in *ObtenerRecomendacionRequest, opts ...grpc.CallOption) (*RecomendacionResponse, error) {
	out := new(RecomendacionResponse)
	err := c.cc.Invoke(ctx, RatingService_ObtenerRecomendacion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) ObtenerCalificacionUsuario(ctx context.Context, in *ObtenerCalificacionUsuarioRequest, opts ...grpc.CallOption) (*CalificacionUsuarioResponse, error) {
	out := new(CalificacionUsuarioResponse)
	err := c.cc.Invoke(ctx, RatingService_ObtenerCalificacionUsuario_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServiceServer is the server API for RatingService service.
// All implementations must embed UnimplementedRatingServiceServer
// for forward compatibility
type RatingServiceServer interface {
	Calificar(context.Context, *CalificarRequest) (*RecomendacionResponse, error)
	ObtenerRecomendacion(context.Context, *ObtenerRecomendacionRequest) (*RecomendacionResponse, error)
	ObtenerCalificacionUsuario(context.Context, *ObtenerCalificacionUsuarioRequest) (*CalificacionUsuarioResponse, error)
	mustEmbedUnimplementedRatingServiceServer()
}

// UnimplementedRatingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRatingServiceServer struct {
}

func (UnimplementedRatingServiceServer) Calificar(context.Context, *CalificarRequest) (*RecomendacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calificar not implemented")
}
func (UnimplementedRatingServiceServer) ObtenerRecomendacion(context.Context, *ObtenerRecomendacionRequest) (*RecomendacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerRecomendacion not implemented")
}
func (UnimplementedRatingServiceServer) ObtenerCalificacionUsuario(context.Context, *ObtenerCalificacionUsuarioRequest) (*CalificacionUsuarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerCalificacionUsuario not implemented")
}
func (UnimplementedRatingServiceServer) mustEmbedUnimplementedRatingServiceServer() {}

// UnsafeRatingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServiceServer will
// result in compilation errors.
type UnsafeRatingServiceServer interface {
	mustEmbedUnimplementedRatingServiceServer()
}

func RegisterRatingServiceServer(s grpc.ServiceRegistrar, srv RatingServiceServer) {
	s.RegisterService(&RatingService_ServiceDesc, srv)
}

func _RatingService_Calificar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalificarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).Calificar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_Calificar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).Calificar(ctx, req.(*CalificarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_ObtenerRecomendacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerRecomendacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).ObtenerRecomendacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_ObtenerRecomendacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).ObtenerRecomendacion(ctx, req.(*ObtenerRecomendacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_ObtenerCalificacionUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerCalificacionUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).ObtenerCalificacionUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_ObtenerCalificacionUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).ObtenerCalificacionUsuario(ctx, req.(*ObtenerCalificacionUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatingService_ServiceDesc is the grpc.ServiceDesc for RatingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rating.v1.RatingService",
	HandlerType: (*RatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calificar",
			Handler:    _RatingService_Calificar_Handler,
		},
		{
			MethodName: "ObtenerRecomendacion",
			Handler:    _RatingService_ObtenerRecomendacion_Handler,
		},
		{
			MethodName: "ObtenerCalificacionUsuario",
			Handler:    _RatingService_ObtenerCalificacionUsuario_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rating.proto",
}
