// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/watchparty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrearSalaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearSalaRequest) Reset() {
	*x = CrearSalaRequest{}
	mi := &file_proto_watchparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearSalaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearSalaRequest) ProtoMessage() {}

func (x *CrearSalaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearSalaRequest.ProtoReflect.Descriptor instead.
func (*CrearSalaRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchparty_proto_rawDescGZIP(), []int{0}
}

func (x *CrearSalaRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *CrearSalaRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type SalaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodigoSala    string                 `protobuf:"bytes,1,opt,name=codigo_sala,json=codigoSala,proto3" json:"codigo_sala,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	CreadorId     string                 `protobuf:"bytes,3,opt,name=creador_id,json=creadorId,proto3" json:"creador_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaResponse) Reset() {
	*x = SalaResponse{}
	mi := &file_proto_watchparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaResponse) ProtoMessage() {}

func (x *SalaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaResponse.ProtoReflect.Descriptor instead.
func (*SalaResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchparty_proto_rawDescGZIP(), []int{1}
}

func (x *SalaResponse) GetCodigoSala() string {
	if x != nil {
		return x.CodigoSala
	}
	return ""
}

func (x *SalaResponse) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *SalaResponse) GetCreadorId() string {
	if x != nil {
		return x.CreadorId
	}
	return ""
}

type ValidarSalaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodigoSala    string                 `protobuf:"bytes,1,opt,name=codigo_sala,json=codigoSala,proto3" json:"codigo_sala,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarSalaRequest) Reset() {
	*x = ValidarSalaRequest{}
	mi := &file_proto_watchparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarSalaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarSalaRequest) ProtoMessage() {}

func (x *ValidarSalaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarSalaRequest.ProtoReflect.Descriptor instead.
func (*ValidarSalaRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchparty_proto_rawDescGZIP(), []int{2}
}

func (x *ValidarSalaRequest) GetCodigoSala() string {
	if x != nil {
		return x.CodigoSala
	}
	return ""
}

type ValidarSalaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existe        bool                   `protobuf:"varint,1,opt,name=existe,proto3" json:"existe,omitempty"`
	ContenidoId   string                 `protobuf:"bytes,2,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarSalaResponse) Reset() {
	*x = ValidarSalaResponse{}
	mi := &file_proto_watchparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarSalaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarSalaResponse) ProtoMessage() {}

func (x *ValidarSalaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarSalaResponse.ProtoReflect.Descriptor instead.
func (*ValidarSalaResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchparty_proto_rawDescGZIP(), []int{3}
}

func (x *ValidarSalaResponse) GetExiste() bool {
	if x != nil {
		return x.Existe
	}
	return false
}

func (x *ValidarSalaResponse) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

var File_proto_watchparty_proto protoreflect.FileDescriptor

const file_proto_watchparty_proto_rawDesc = "" +
	"\n" +
	"\x16proto/watchparty.proto\x12\rwatchparty.v1\"T\n" +
	"\x10CrearSalaRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId\"q\n" +
	"\fSalaResponse\x12\x1f\n" +
	"\vcodigo_sala\x18\x01 \x01(\tR\n" +
	"codigoSala\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId\x12\x1d\n" +
	"\n" +
	"creador_id\x18\x03 \x01(\tR\tcreadorId\"5\n" +
	"\x12ValidarSalaRequest\x12\x1f\n" +
	"\vcodigo_sala\x18\x01 \x01(\tR\n" +
	"codigoSala\"P\n" +
	"\x13ValidarSalaResponse\x12\x16\n" +
	"\x06existe\x18\x01 \x01(\bR\x06existe\x12!\n" +
	"\fcontenido_id\x18\x02 \x01(\tR\vcontenidoId2\xb4\x01\n" +
	"\x11WatchPartyService\x12I\n" +
	"\tCrearSala\x12\x1f.watchparty.v1.CrearSalaRequest\x1a\x1b.watchparty.v1.SalaResponse\x12T\n" +
	"\vValidarSala\x12!.watchparty.v1.ValidarSalaRequest\x1a\".watchparty.v1.ValidarSalaResponseB4Z2github.com/grupo4/quetxaltv-gateway/internal/pb;pbb\x06proto3"

var (
	file_proto_watchparty_proto_rawDescOnce sync.Once
	file_proto_watchparty_proto_rawDescData []byte
)

func file_proto_watchparty_proto_rawDescGZIP() []byte {
	file_proto_watchparty_proto_rawDescOnce.Do(func() {
		file_proto_watchparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_watchparty_proto_rawDesc), len(file_proto_watchparty_proto_rawDesc)))
	})
	return file_proto_watchparty_proto_rawDescData
}

var file_proto_watchparty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_watchparty_proto_goTypes = []any{
	(*CrearSalaRequest)(nil),    // 0: watchparty.v1.CrearSalaRequest
	(*SalaResponse)(nil),        // 1: watchparty.v1.SalaResponse
	(*ValidarSalaRequest)(nil),  // 2: watchparty.v1.ValidarSalaRequest
	(*ValidarSalaResponse)(nil), // 3: watchparty.v1.ValidarSalaResponse
}
var file_proto_watchparty_proto_depIdxs = []int32{
	0, // 0: watchparty.v1.WatchPartyService.CrearSala:input_type -> watchparty.v1.CrearSalaRequest
	2, // 1: watchparty.v1.WatchPartyService.ValidarSala:input_type -> watchparty.v1.ValidarSalaRequest
	1, // 2: watchparty.v1.WatchPartyService.CrearSala:output_type -> watchparty.v1.SalaResponse
	3, // 3: watchparty.v1.WatchPartyService.ValidarSala:output_type -> watchparty.v1.ValidarSalaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_watchparty_proto_init() }
func file_proto_watchparty_proto_init() {
	if File_proto_watchparty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_watchparty_proto_rawDesc), len(file_proto_watchparty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_watchparty_proto_goTypes,
		DependencyIndexes: file_proto_watchparty_proto_depIdxs,
		MessageInfos:      file_proto_watchparty_proto_msgTypes,
	}.Build()
	File_proto_watchparty_proto = out.File
	file_proto_watchparty_proto_goTypes = nil
	file_proto_watchparty_proto_depIdxs = nil
}
