// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/watchparty.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WatchPartyService_CrearSala_FullMethodName   = "/watchparty.v1.WatchPartyService/CrearSala"
	WatchPartyService_ValidarSala_FullMethodName = "/watchparty.v1.WatchPartyService/ValidarSala"
)

// WatchPartyServiceClient is the client API for WatchPartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchPartyServiceClient interface {
	CrearSala(ctx context.Context, in *CrearSalaRequest, opts ...grpc.CallOption) (*SalaResponse, error)
	ValidarSala(ctx context.Context, in *ValidarSalaRequest, opts ...grpc.CallOption) (*ValidarSalaResponse, error)
}

type watchPartyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchPartyServiceClient(cc grpc.ClientConnInterface) WatchPartyServiceClient {
	return &watchPartyServiceClient{cc}
}

func (c *watchPartyServiceClient) CrearSala(ctx context.Context, in *CrearSalaRequest, opts ...grpc.CallOption) (*SalaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalaResponse)
	err := c.cc.Invoke(ctx, WatchPartyService_CrearSala_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchPartyServiceClient) ValidarSala(ctx context.Context, in *ValidarSalaRequest, opts ...grpc.CallOption) (*ValidarSalaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidarSalaResponse)
	err := c.cc.Invoke(ctx, WatchPartyService_ValidarSala_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchPartyServiceServer is the server API for WatchPartyService service.
// All implementations must embed UnimplementedWatchPartyServiceServer
// for forward compatibility.
type WatchPartyServiceServer interface {
	CrearSala(context.Context, *CrearSalaRequest) (*SalaResponse, error)
	ValidarSala(context.Context, *ValidarSalaRequest) (*ValidarSalaResponse, error)
	mustEmbedUnimplementedWatchPartyServiceServer()
}

// UnimplementedWatchPartyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchPartyServiceServer struct{}

func (UnimplementedWatchPartyServiceServer) CrearSala(context.Context, *CrearSalaRequest) (*SalaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearSala not implemented")
}
func (UnimplementedWatchPartyServiceServer) ValidarSala(context.Context, *ValidarSalaRequest) (*ValidarSalaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidarSala not implemented")
}
func (UnimplementedWatchPartyServiceServer) mustEmbedUnimplementedWatchPartyServiceServer() {}
func (UnimplementedWatchPartyServiceServer) testEmbeddedByValue()                           {}

// UnsafeWatchPartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchPartyServiceServer will
// result in compilation errors.
type UnsafeWatchPartyServiceServer interface {
	mustEmbedUnimplementedWatchPartyServiceServer()
}

func RegisterWatchPartyServiceServer(s grpc.ServiceRegistrar, srv WatchPartyServiceServer) {
	// If the following call panics, it indicates UnimplementedWatchPartyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchPartyService_ServiceDesc, srv)
}

func _WatchPartyService_CrearSala_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearSalaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchPartyServiceServer).CrearSala(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchPartyService_CrearSala_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchPartyServiceServer).CrearSala(ctx, req.(*CrearSalaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchPartyService_ValidarSala_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidarSalaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchPartyServiceServer).ValidarSala(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchPartyService_ValidarSala_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchPartyServiceServer).ValidarSala(ctx, req.(*ValidarSalaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchPartyService_ServiceDesc is the grpc.ServiceDesc for WatchPartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchPartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchparty.v1.WatchPartyService",
	HandlerType: (*WatchPartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearSala",
			Handler:    _WatchPartyService_CrearSala_Handler,
		},
		{
			MethodName: "ValidarSala",
			Handler:    _WatchPartyService_ValidarSala_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/watchparty.proto",
}
