@startuml
skinparam componentStyle uml2
left to right direction

title Vista de Componentes y Persistencia (Nivel PIM) - Quetxal TV

actor "Cliente Web/Móvil" as cliente

package "Capa Perimetral" {
  [Frontend (SPA)] as front
  [API Gateway] as apigw
}

cliente --> front : HTTP/HTTPS (Web)
front ..> apigw : Peticiones AJAX/REST (JWT)

package "Ecosistema de Microservicios (Backend Políglota)" {
  [auth-service\n<<Go>>] as auth
  [catalog-service\n<<Python>>] as cat
  [billing-service\n<<TypeScript>>] as bill
  [fx-service\n<<Python>>] as fx
  [history-service\n<<Go>>] as hist
  [notification-service\n<<TypeScript>>] as notif
  [rating-service\n<<Python>>] as rat
}

apigw --> auth : gRPC
apigw --> cat : gRPC
apigw --> bill : gRPC
apigw --> fx : gRPC
apigw --> hist : gRPC
apigw --> notif : gRPC
apigw --> rat : gRPC

' Comunicaciones inter-microservicios
bill --> fx : gRPC (Tasas)
bill --> notif : gRPC (Recibos)
cat --> notif : gRPC (Alertas)
rat --> cat : gRPC (Votos)

package "Capa de Persistencia y Caché" {
  database "auth-db\n(PostgreSQL)" as db_auth {
      [Tabla Usuarios]
      [Trigger Auditoría]
      [Tabla Audit]
  }
  database "catalog-db\n(PostgreSQL)" as db_cat {
      [Tabla Peliculas/Series]
      [Trigger Auditoría]
      [Tabla Audit_Cat]
  }
  database "rating-db\n(PostgreSQL)" as db_rat
  database "subscription-db\n(PostgreSQL)" as db_sub {
      [Tabla Suscripciones]
      [Trigger Auditoría]
      [Tabla Audit_Sub]
  }
  database "fx-db\n(PostgreSQL)" as db_fx
  database "redis\n(Caché)" as db_redis
  database "history-db\n(PostgreSQL)" as db_hist {
      [Tabla Progreso]
      [Trigger Auditoría]
      [Tabla Audit_Hist]
  }
  database "notification-db\n(PostgreSQL)" as db_notif
}

auth --> db_auth : TCP :5432
cat --> db_cat : TCP :5432
rat --> db_rat : TCP :5432
bill --> db_sub : TCP :5432
fx --> db_fx : TCP :5432
fx --> db_redis : TCP :6379
hist --> db_hist : TCP :5432
notif --> db_notif : TCP :5432

package "Capa de Servicios Externos de la Nube" {
  [Google Cloud Storage (GCS)] as gcs
  [API Externa Monedas] as ext_fx
  [Servidor SMTP] as ext_smtp
}

cat --> gcs : Subida de Media / HMAC
fx --> ext_fx : REST/HTTP
notif --> ext_smtp : SMTP

note bottom of front
  El Frontend consume directamente 
  el Streaming de Video usando la 
  URL Firmada generada por catalog.
end note

@enduml
