// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email        string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password     string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NombrePerfil string `protobuf:"bytes,3,opt,name=nombre_perfil,json=nombrePerfil,proto3" json:"nombre_perfil,omitempty"` // nombre del primer perfil
}

func (x *RegistrarRequest) Reset() {
	*x = RegistrarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarRequest) ProtoMessage() {}

func (x *RegistrarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarRequest.ProtoReflect.Descriptor instead.
func (*RegistrarRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrarRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrarRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrarRequest) GetNombrePerfil() string {
	if x != nil {
		return x.NombrePerfil
	}
	return ""
}

type RegistrarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioId string `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	PerfilId  string `protobuf:"bytes,2,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
}

func (x *RegistrarResponse) Reset() {
	*x = RegistrarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarResponse) ProtoMessage() {}

func (x *RegistrarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarResponse.ProtoReflect.Descriptor instead.
func (*RegistrarResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrarResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *RegistrarResponse) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // JWT firmado (HS256)
	UsuarioId   string `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	ExpiraEn    int64  `protobuf:"varint,3,opt,name=expira_en,json=expiraEn,proto3" json:"expira_en,omitempty"` // timestamp unix de expiracion
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *LoginResponse) GetExpiraEn() int64 {
	if x != nil {
		return x.ExpiraEn
	}
	return 0
}

type ValidarTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ValidarTokenRequest) Reset() {
	*x = ValidarTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidarTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenRequest) ProtoMessage() {}

func (x *ValidarTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidarTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ValidarTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidarTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valido    bool   `protobuf:"varint,1,opt,name=valido,proto3" json:"valido,omitempty"`
	UsuarioId string `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Rol       string `protobuf:"bytes,3,opt,name=rol,proto3" json:"rol,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ValidarTokenResponse) Reset() {
	*x = ValidarTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidarTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenResponse) ProtoMessage() {}

func (x *ValidarTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidarTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidarTokenResponse) GetValido() bool {
	if x != nil {
		return x.Valido
	}
	return false
}

func (x *ValidarTokenResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ValidarTokenResponse) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

func (x *ValidarTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CrearPerfilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioId  string `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Nombre     string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	EsInfantil bool   `protobuf:"varint,3,opt,name=es_infantil,json=esInfantil,proto3" json:"es_infantil,omitempty"`
	Idioma     string `protobuf:"bytes,4,opt,name=idioma,proto3" json:"idioma,omitempty"` // 'es' | 'en' | 'pt' | 'fr'
}

func (x *CrearPerfilRequest) Reset() {
	*x = CrearPerfilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrearPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPerfilRequest) ProtoMessage() {}

func (x *CrearPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPerfilRequest.ProtoReflect.Descriptor instead.
func (*CrearPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CrearPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *CrearPerfilRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CrearPerfilRequest) GetEsInfantil() bool {
	if x != nil {
		return x.EsInfantil
	}
	return false
}

func (x *CrearPerfilRequest) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

type PerfilResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre     string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	EsInfantil bool   `protobuf:"varint,3,opt,name=es_infantil,json=esInfantil,proto3" json:"es_infantil,omitempty"`
	Idioma     string `protobuf:"bytes,4,opt,name=idioma,proto3" json:"idioma,omitempty"`
}

func (x *PerfilResponse) Reset() {
	*x = PerfilResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfilResponse) ProtoMessage() {}

func (x *PerfilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfilResponse.ProtoReflect.Descriptor instead.
func (*PerfilResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *PerfilResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PerfilResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PerfilResponse) GetEsInfantil() bool {
	if x != nil {
		return x.EsInfantil
	}
	return false
}

func (x *PerfilResponse) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

type EditarPerfilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioId  string `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	PerfilId   string `protobuf:"bytes,2,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	Nombre     string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	EsInfantil bool   `protobuf:"varint,4,opt,name=es_infantil,json=esInfantil,proto3" json:"es_infantil,omitempty"`
	Idioma     string `protobuf:"bytes,5,opt,name=idioma,proto3" json:"idioma,omitempty"`
}

func (x *EditarPerfilRequest) Reset() {
	*x = EditarPerfilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditarPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditarPerfilRequest) ProtoMessage() {}

func (x *EditarPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditarPerfilRequest.ProtoReflect.Descriptor instead.
func (*EditarPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *EditarPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *EditarPerfilRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *EditarPerfilRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *EditarPerfilRequest) GetEsInfantil() bool {
	if x != nil {
		return x.EsInfantil
	}
	return false
}

func (x *EditarPerfilRequest) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

type ListarPerfilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioId string `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
}

func (x *ListarPerfilesRequest) Reset() {
	*x = ListarPerfilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListarPerfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPerfilesRequest) ProtoMessage() {}

func (x *ListarPerfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPerfilesRequest.ProtoReflect.Descriptor instead.
func (*ListarPerfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ListarPerfilesRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type ListarPerfilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perfiles []*PerfilResponse `protobuf:"bytes,1,rep,name=perfiles,proto3" json:"perfiles,omitempty"`
}

func (x *ListarPerfilesResponse) Reset() {
	*x = ListarPerfilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListarPerfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPerfilesResponse) ProtoMessage() {}

func (x *ListarPerfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPerfilesResponse.ProtoReflect.Descriptor instead.
func (*ListarPerfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ListarPerfilesResponse) GetPerfiles() []*PerfilResponse {
	if x != nil {
		return x.Perfiles
	}
	return nil
}

type ActualizarPerfilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsuarioId string `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Nombre    string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *ActualizarPerfilRequest) Reset() {
	*x = ActualizarPerfilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualizarPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarPerfilRequest) ProtoMessage() {}

func (x *ActualizarPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarPerfilRequest.ProtoReflect.Descriptor instead.
func (*ActualizarPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ActualizarPerfilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ActualizarPerfilRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type EliminarPerfilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsuarioId string `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
}

func (x *EliminarPerfilRequest) Reset() {
	*x = EliminarPerfilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EliminarPerfilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarPerfilRequest) ProtoMessage() {}

func (x *EliminarPerfilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarPerfilRequest.ProtoReflect.Descriptor instead.
func (*EliminarPerfilRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *EliminarPerfilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EliminarPerfilRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

type EliminarPerfilResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *EliminarPerfilResponse) Reset() {
	*x = EliminarPerfilResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EliminarPerfilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarPerfilResponse) ProtoMessage() {}

func (x *EliminarPerfilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarPerfilResponse.ProtoReflect.Descriptor instead.
func (*EliminarPerfilResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *EliminarPerfilResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_auth_proto protoreflect.FileDescriptor

var file_proto_auth_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x69, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x66,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x22, 0x4f, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65,
	0x72, 0x66, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x65, 0x72, 0x66, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x6e, 0x0a, 0x0d, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x5f, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x45, 0x6e, 0x22, 0x2b, 0x0a, 0x13, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x75, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x84, 0x01,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x73, 0x5f, 0x69, 0x6e, 0x66, 0x61, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x61, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x64, 0x69, 0x6f, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64,
	0x69, 0x6f, 0x6d, 0x61, 0x22, 0x71, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x61, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x61, 0x6e, 0x74, 0x69, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x64, 0x69, 0x6f, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x64, 0x69, 0x6f, 0x6d, 0x61, 0x22, 0xa2, 0x01, 0x0a, 0x13, 0x45, 0x64, 0x69, 0x74,
	0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x61, 0x6e, 0x74,
	0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x61,
	0x6e, 0x74, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x69, 0x6f, 0x6d, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x69, 0x6f, 0x6d, 0x61, 0x22, 0x36, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65,
	0x72, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x08, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x70, 0x65, 0x72, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x60, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x46, 0x0a, 0x15, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61,
	0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x22, 0x32, 0x0a,
	0x16, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0xd7, 0x04, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x42, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x12, 0x19,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x0c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x72, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0c, 0x45, 0x64, 0x69, 0x74, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x12,
	0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x61, 0x72,
	0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72,
	0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x10, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x12, 0x20, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x45, 0x6c, 0x69, 0x6d,
	0x69, 0x6e, 0x61, 0x72, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x12, 0x1e, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x50, 0x65, 0x72,
	0x66, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x50, 0x65, 0x72,
	0x66, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x34,
	0x2f, 0x71, 0x75, 0x65, 0x74, 0x78, 0x61, 0x6c, 0x74, 0x76, 0x2d, 0x61, 0x75, 0x74, 0x68, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData = file_proto_auth_proto_rawDesc
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_auth_proto_rawDescData)
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_auth_proto_goTypes = []interface{}{
	(*RegistrarRequest)(nil),        // 0: auth.v1.RegistrarRequest
	(*RegistrarResponse)(nil),       // 1: auth.v1.RegistrarResponse
	(*LoginRequest)(nil),            // 2: auth.v1.LoginRequest
	(*LoginResponse)(nil),           // 3: auth.v1.LoginResponse
	(*ValidarTokenRequest)(nil),     // 4: auth.v1.ValidarTokenRequest
	(*ValidarTokenResponse)(nil),    // 5: auth.v1.ValidarTokenResponse
	(*CrearPerfilRequest)(nil),      // 6: auth.v1.CrearPerfilRequest
	(*PerfilResponse)(nil),          // 7: auth.v1.PerfilResponse
	(*EditarPerfilRequest)(nil),     // 8: auth.v1.EditarPerfilRequest
	(*ListarPerfilesRequest)(nil),   // 9: auth.v1.ListarPerfilesRequest
	(*ListarPerfilesResponse)(nil),  // 10: auth.v1.ListarPerfilesResponse
	(*ActualizarPerfilRequest)(nil), // 11: auth.v1.ActualizarPerfilRequest
	(*EliminarPerfilRequest)(nil),   // 12: auth.v1.EliminarPerfilRequest
	(*EliminarPerfilResponse)(nil),  // 13: auth.v1.EliminarPerfilResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	7,  // 0: auth.v1.ListarPerfilesResponse.perfiles:type_name -> auth.v1.PerfilResponse
	0,  // 1: auth.v1.AuthService.Registrar:input_type -> auth.v1.RegistrarRequest
	2,  // 2: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	4,  // 3: auth.v1.AuthService.ValidarToken:input_type -> auth.v1.ValidarTokenRequest
	6,  // 4: auth.v1.AuthService.CrearPerfil:input_type -> auth.v1.CrearPerfilRequest
	8,  // 5: auth.v1.AuthService.EditarPerfil:input_type -> auth.v1.EditarPerfilRequest
	9,  // 6: auth.v1.AuthService.ListarPerfiles:input_type -> auth.v1.ListarPerfilesRequest
	11, // 7: auth.v1.AuthService.ActualizarPerfil:input_type -> auth.v1.ActualizarPerfilRequest
	12, // 8: auth.v1.AuthService.EliminarPerfil:input_type -> auth.v1.EliminarPerfilRequest
	1,  // 9: auth.v1.AuthService.Registrar:output_type -> auth.v1.RegistrarResponse
	3,  // 10: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	5,  // 11: auth.v1.AuthService.ValidarToken:output_type -> auth.v1.ValidarTokenResponse
	7,  // 12: auth.v1.AuthService.CrearPerfil:output_type -> auth.v1.PerfilResponse
	7,  // 13: auth.v1.AuthService.EditarPerfil:output_type -> auth.v1.PerfilResponse
	10, // 14: auth.v1.AuthService.ListarPerfiles:output_type -> auth.v1.ListarPerfilesResponse
	7,  // 15: auth.v1.AuthService.ActualizarPerfil:output_type -> auth.v1.PerfilResponse
	13, // 16: auth.v1.AuthService.EliminarPerfil:output_type -> auth.v1.EliminarPerfilResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidarTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidarTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrearPerfilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerfilResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditarPerfilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListarPerfilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListarPerfilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualizarPerfilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EliminarPerfilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EliminarPerfilResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_rawDesc = nil
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
