apiVersion: v1
kind: Secret
metadata:
  name: quetxal-secrets
  namespace: quetxal-tv-prod
type: Opaque
# NOTA IMPORTANTE: Este es un archivo plantilla. 
# Por regla de seguridad (Requisito 8), NUNCA hardcodear contraseñas reales aquí.
# Durante el CI/CD, estos valores deben ser reemplazados usando sed o envsubst con los GitHub Secrets
stringData:
  # Databases
  AUTH_DB_NAME: "reemplazar_en_cicd"
  AUTH_DB_USER: "reemplazar_en_cicd"
  AUTH_DB_PASSWORD: "reemplazar_en_cicd"

  SUBSCRIPTION_DB_NAME: "reemplazar_en_cicd"
  SUBSCRIPTION_DB_USER: "reemplazar_en_cicd"
  SUBSCRIPTION_DB_PASSWORD: "reemplazar_en_cicd"

  CATALOG_DB_NAME: "reemplazar_en_cicd"
  CATALOG_DB_USER: "reemplazar_en_cicd"
  CATALOG_DB_PASSWORD: "reemplazar_en_cicd"

  RATING_DB_NAME: "reemplazar_en_cicd"
  RATING_DB_USER: "reemplazar_en_cicd"
  RATING_DB_PASSWORD: "reemplazar_en_cicd"

  FX_DB_NAME: "reemplazar_en_cicd"
  FX_DB_USER: "reemplazar_en_cicd"
  FX_DB_PASSWORD: "reemplazar_en_cicd"

  HISTORY_DB_NAME: "reemplazar_en_cicd"
  HISTORY_DB_USER: "reemplazar_en_cicd"
  HISTORY_DB_PASSWORD: "reemplazar_en_cicd"

  NOTIFICATION_DB_NAME: "reemplazar_en_cicd"
  NOTIFICATION_DB_USER: "reemplazar_en_cicd"
  NOTIFICATION_DB_PASSWORD: "reemplazar_en_cicd"

  REDIS_PASSWORD: "reemplazar_en_cicd"

  # App Secrets
  JWT_SECRET: "reemplazar_en_cicd"

  # FX API Settings
  FX_API_URL: "reemplazar_en_cicd"
  FX_API_TIMEOUT: "reemplazar_en_cicd"
  FX_CACHE_TTL: "reemplazar_en_cicd"

  # SMTP Notification
  SMTP_HOST: "reemplazar_en_cicd"
  SMTP_USER: "reemplazar_en_cicd"
  SMTP_PASS: "reemplazar_en_cicd"
  SMTP_FROM: "reemplazar_en_cicd"

  # GCS (Para la tarea 2 en el futuro)
  GCS_ACCESS_KEY: "reemplazar_en_cicd"
  GCS_SECRET_KEY: "reemplazar_en_cicd"
  GCS_BUCKET_NAME: "reemplazar_en_cicd"
